import assert from 'node:assert/strict';
import test from 'node:test';
import { existsSync, readFileSync } from 'node:fs';
import vm from 'node:vm';

const moduleUrl=new URL('../data/apwh-u9-location-study.js',import.meta.url);
const ledgerUrl=new URL('../docs/data-sources/apwh-u9-location-study-source-ledger.md',import.meta.url);
const source=existsSync(moduleUrl)?readFileSync(moduleUrl,'utf8'):'';
const ledger=existsSync(ledgerUrl)?readFileSync(ledgerUrl,'utf8'):'';
const evaluateSandbox=(code=source,seed={})=>{const sandbox={...seed};sandbox.window=sandbox;vm.runInNewContext(code,sandbox);return sandbox;};
const evaluate=(code=source,seed={})=>evaluateSandbox(code,seed).APWH_U9_LOCATION_STUDY;
const expectedLocations=new Map([
  ['11','Food Security & Unequal Inputs · India / Amritsar–Punjab'],
  ['70','Digital Infrastructure & Knowledge Economy · United States / San Francisco'],
  ['15','Special Economic Zones & Export Manufacturing · China / Guangzhou'],
  ['65','Free Trade & Maquiladoras · Mexico / Ciudad Juárez'],
  ['5','Market Reform & Political Control · China / Beijing'],
  ['54','Global Financial Governance · United States / Washington, D.C.'],
  ['112','Resistance to Globalization · United States / Seattle'],
  ['24','Human Rights & Climate Governance · France / Paris'],
  ['34','Global Health Cooperation · Switzerland / Geneva'],
  ['110','Digital Culture & Soft Power · South Korea / Seoul'],
]);
const expectedBindings=new Map([
  ['11','world-event-11-3'],['70','world-event-70-2'],['15','world-event-15-1'],['65','world-event-65-0'],['5','world-event-5-13'],['54','world-event-54-5'],['112','world-event-112-0'],['24','world-event-24-9'],['34','world-event-34-2'],['110','world-event-110-1'],
]);
const ledgerIntroduction='# APWH Unit 9 Location Study Source Ledger\n\nThe learner records use edition-neutral locators in AMSCO AP World History Unit 9 and the College Board framework effective Fall 2026. Map pins are representative anchors; a named city does not imply that every national or global process occurred only there. Institutional labels remain distinct, and project-authored causal or comparison analysis is identified separately from sourced facts.';
const ledgerHeader='| Stable ID | AP topic assignment | Main event | Source locator | Claims covered and caveat |';
const ledgerSeparator='| --- | --- | --- | --- | --- |';
const expectedLedgerRows=[
  ['apwh-u9-amritsar-high-yield-seeds-input-package','9.1, 9.3','world-event-11-3','AMSCO AP World History, Unit 9, Topics 9.1 and 9.3','High-yield varieties required irrigation, fertilizer, credit, land, and machinery. Amritsar–Punjab is a representative regional anchor, not the sole site of India’s Green Revolution; the local causal link is project-authored analysis.'],
  ['apwh-u9-amritsar-unequal-access-land-consolidation','9.3, 9.4','world-event-11-3','AMSCO AP World History, Unit 9, Topics 9.3 and 9.4','Unequal access favored larger landholders and changed labor demand. The comparison with Guangzhou distinguishes input-intensive agriculture from export manufacturing and is project-authored analysis.'],
  ['apwh-u9-amritsar-food-population-environmental-costs','9.3, 9.9','world-event-11-3','AMSCO AP World History, Unit 9, Topics 9.3 and 9.9','Higher food output supported population while intensive irrigation and chemicals strained water and soil across Punjab; the causal synthesis is project-authored analysis.'],
  ['apwh-u9-san-francisco-public-research-digital-infrastructure','9.1','world-event-70-2','AMSCO AP World History, Unit 9, Topic 9.1','Public research, procurement, universities, semiconductors, and skilled labor supported computing. San Francisco represents the wider Bay Area and does not claim sole invention; the causal link is project-authored analysis.'],
  ['apwh-u9-san-francisco-computing-internet-information-costs','9.1, 9.4','world-event-70-2','AMSCO AP World History, Unit 9, Topics 9.1 and 9.4','Computing and interoperable internet networks lowered information costs. San Francisco is one commercialization anchor, and the cross-link to Seoul is project-authored causal analysis.'],
  ['apwh-u9-san-francisco-knowledge-economy-distributed-production','9.4, 9.9','world-event-70-2','AMSCO AP World History, Unit 9, Topics 9.4 and 9.9','Digital firms concentrated design and software while distributing production and support work internationally; the uneven-gains conclusion is project-authored analysis.'],
  ['apwh-u9-guangzhou-market-reform-special-economic-zones','9.4','world-event-15-1','AMSCO AP World History, Unit 9, Topic 9.4','Chinese leaders unilaterally authorized market reforms and coastal special economic zones while retaining party control; Guangzhou represents the Pearl River Delta, and the causal link is project-authored analysis.'],
  ['apwh-u9-guangzhou-foreign-investment-export-manufacturing','9.4','world-event-15-1','AMSCO AP World History, Unit 9, Topic 9.4','Foreign direct investment, labor, infrastructure, and port access expanded export manufacturing. Cross-links to Beijing and Ciudad Juárez are project-authored analysis, not sourced chronology.'],
  ['apwh-u9-guangzhou-supply-chain-labor-environmental-costs','9.3, 9.4, 9.9','world-event-15-1','AMSCO AP World History, Unit 9, Topics 9.3, 9.4, and 9.9','WTO-era supply chains drew migrant labor and produced factory pollution. The Amritsar comparison distinguishes manufacturing from agriculture and is project-authored analysis.'],
  ['apwh-u9-ciudad-juarez-border-industrialization','9.4','world-event-65-0','AMSCO AP World History, Unit 9, Topic 9.4','Mexico’s 1965 Border Industrialization Program created an assembly base before NAFTA; Ciudad Juárez is a representative border anchor, and the local causal link is project-authored analysis.'],
  ['apwh-u9-ciudad-juarez-nafta-maquiladora-expansion','9.4','world-event-65-0','AMSCO AP World History, Unit 9, Topic 9.4','NAFTA’s negotiated North American rules expanded an existing maquiladora system. The Guangzhou comparison distinguishes the agreement from unilateral Chinese reform and is project-authored analysis.'],
  ['apwh-u9-ciudad-juarez-employment-gender-labor-environment','9.3, 9.4, 9.9','world-event-65-0','AMSCO AP World History, Unit 9, Topics 9.3, 9.4, and 9.9','Maquiladora expansion changed employment and gender patterns while raising labor and pollution disputes. Ciudad Juárez is not the whole border economy; the cross-link to Seattle is project-authored causal analysis.'],
  ['apwh-u9-beijing-market-reform-political-control','9.4, 9.5','world-event-5-13','AMSCO AP World History, Unit 9, Topics 9.4 and 9.5','Market reform proceeded without political liberalization under one-party rule. Beijing is a national-policy anchor, and the local causal link is project-authored analysis.'],
  ['apwh-u9-beijing-tiananmen-protest-repression','9.5','world-event-5-13','AMSCO AP World History, Unit 9, Topic 9.5','Students and workers organized protest before the one-party state chose military repression. The Seattle comparison distinguishes repression from pluralist summit protest and is project-authored analysis.'],
  ['apwh-u9-beijing-wto-integration-information-control','9.4, 9.5, 9.9','world-event-5-13','AMSCO AP World History, Unit 9, Topics 9.4, 9.5, and 9.9','WTO integration coexisted with party information controls and did not cause democratization; the Guangzhou-to-Beijing mechanism is project-authored causal analysis.'],
  ['apwh-u9-washington-bretton-woods-financial-institutions','9.8','world-event-54-5','AMSCO AP World History, Unit 9, Topic 9.8','Bretton Woods created the IMF and World Bank. Washington, D.C. is a headquarters anchor; the World Bank, IMF, and WTO remain distinct institutions, and the causal link is project-authored analysis.'],
  ['apwh-u9-washington-development-lending-conditionality','9.4, 9.8','world-event-54-5','AMSCO AP World History, Unit 9, Topics 9.4 and 9.8','Development lending and conditionality shaped borrower policy with contested outcomes. The link to Seattle concerns institutional accountability and is project-authored causal analysis.'],
  ['apwh-u9-washington-institutional-power-benefits-criticism','9.7, 9.8, 9.9','world-event-54-5','AMSCO AP World History, Unit 9, Topics 9.7, 9.8, and 9.9','Weighted voting and lending power generated benefits and criticism. The Paris comparison distinguishes financial conditionality from voluntary rights-and-climate commitments and is project-authored analysis.'],
  ['apwh-u9-seattle-wto-expansion-rulemaking-criticism','9.7, 9.8','world-event-112-0','AMSCO AP World History, Unit 9, Topics 9.7 and 9.8','WTO rule-making criticism concerned labor, environment, sovereignty, and transparency. Seattle anchors a global summit, while the Washington-to-Seattle link is project-authored causal analysis.'],
  ['apwh-u9-seattle-coalition-protest-digital-organization','9.1, 9.5, 9.7','world-event-112-0','AMSCO AP World History, Unit 9, Topics 9.1, 9.5, and 9.7','Labor, environmental, and other groups used digital organization during pluralist summit protest. Comparisons with Beijing and the cross-link from Ciudad Juárez are project-authored analysis.'],
  ['apwh-u9-seattle-fair-trade-labor-continuing-resistance','9.5, 9.7, 9.9','world-event-112-0','AMSCO AP World History, Unit 9, Topics 9.5, 9.7, and 9.9','Fair-trade, labor, environmental, and global-justice campaigns continued beyond one summit; the local causal link is project-authored analysis.'],
  ['apwh-u9-paris-universal-rights-global-norm','9.5, 9.8','world-event-24-9','AMSCO AP World History, Unit 9, Topics 9.5 and 9.8','The UN General Assembly adopted the Universal Declaration of Human Rights in Paris without automatic enforcement. Paris is a representative diplomacy anchor, and the causal link is project-authored analysis.'],
  ['apwh-u9-paris-kyoto-burden-sharing-debate','9.3, 9.8','world-event-24-9','AMSCO AP World History, Unit 9, Topics 9.3 and 9.8','Kyoto-to-Paris negotiations contested historical responsibility, development, sovereignty, participation, and enforcement; the local causal link is project-authored analysis.'],
  ['apwh-u9-paris-voluntary-climate-governance-limits','9.3, 9.8, 9.9','world-event-24-9','AMSCO AP World History, Unit 9, Topics 9.3, 9.8, and 9.9','The Paris Agreement uses nationally determined contributions, reporting, and review under the UN climate process. Comparisons with Washington and Geneva are project-authored analysis distinguishing voluntary governance and long climate mitigation.'],
  ['apwh-u9-geneva-vaccination-smallpox-eradication','9.2, 9.8','world-event-34-2','AMSCO AP World History, Unit 9, Topics 9.2 and 9.8','WHO coordination, national health workers, local participation, surveillance, and vaccination enabled smallpox eradication. Geneva is a coordination anchor, not the campaign’s sole site; the causal link is project-authored analysis.'],
  ['apwh-u9-geneva-hiv-treatment-unequal-access','9.2, 9.9','world-event-34-2','AMSCO AP World History, Unit 9, Topics 9.2 and 9.9','Effective HIV treatment spread unequally because of patents, prices, infrastructure, stigma, activism, and state capacity; the local causal link is project-authored analysis.'],
  ['apwh-u9-geneva-polio-ebola-coordination-limits','9.2, 9.8, 9.9','world-event-34-2','AMSCO AP World History, Unit 9, Topics 9.2, 9.8, and 9.9','WHO-led polio and Ebola work depended on states and trusted local systems. Geneva is a coordination anchor; comparison with Paris distinguishes targeted disease campaigns from long climate mitigation and is project-authored analysis.'],
  ['apwh-u9-seoul-state-supported-cultural-industries','9.4, 9.6','world-event-110-1','AMSCO AP World History, Unit 9, Topics 9.4 and 9.6','South Korean policy and private creativity built cultural industries and export capacity. Seoul is a representative national anchor, and the local causal link is project-authored analysis.'],
  ['apwh-u9-seoul-digital-platforms-transnational-audiences','9.1, 9.6','world-event-110-1','AMSCO AP World History, Unit 9, Topics 9.1 and 9.6','Broadband, streaming, social media, translation, recommendation systems, and fans built transnational audiences. Seoul is an anchor, and the San Francisco cross-link is project-authored causal analysis.'],
  ['apwh-u9-seoul-hybrid-culture-exports-soft-power','9.6, 9.9','world-event-110-1','AMSCO AP World History, Unit 9, Topics 9.6 and 9.9','Korean creators combined local and global forms into exports and soft power, showing globalization was not synonymous with Americanization; the causal synthesis is project-authored analysis.'],
];
const expectedManifest=[
  ['apwh-u9-amritsar-high-yield-seeds-input-package','11',1,'High-Yield Seeds and Complementary Inputs','1960s–1970s',1960,1979,'world-event-11-3',['9.1','9.3'],['TEC','ENV'],['Contextualization','Causation']],
  ['apwh-u9-amritsar-unequal-access-land-consolidation','11',2,'Unequal Access, Mechanization, and Land Consolidation','1960s–1980s',1960,1989,'world-event-11-3',['9.3','9.4'],['ECN','SIO'],['Causation','Comparison']],
  ['apwh-u9-amritsar-food-population-environmental-costs','11',3,'Food Supply, Population Growth, and Environmental Costs','1970s–2010s',1970,2019,'world-event-11-3',['9.3','9.9'],['ENV','SIO'],['Causation','CCOT']],
  ['apwh-u9-san-francisco-public-research-digital-infrastructure','70',1,'Public Research and Digital Infrastructure','1940s–1980s',1940,1989,'world-event-70-2',['9.1'],['TEC','GOV'],['Contextualization']],
  ['apwh-u9-san-francisco-computing-internet-information-costs','70',2,'Computing, Internet, and Lower Information Costs','1970s–1990s',1970,1999,'world-event-70-2',['9.1','9.4'],['TEC','ECN'],['Causation']],
  ['apwh-u9-san-francisco-knowledge-economy-distributed-production','70',3,'Knowledge Economy and Uneven Global Production','1990s–2010s',1990,2019,'world-event-70-2',['9.4','9.9'],['ECN','SIO'],['Causation','CCOT']],
  ['apwh-u9-guangzhou-market-reform-special-economic-zones','15',1,'Market Reform and Special Economic Zones','1978–1984',1978,1984,'world-event-15-1',['9.4'],['ECN','GOV'],['Contextualization','Causation']],
  ['apwh-u9-guangzhou-foreign-investment-export-manufacturing','15',2,'Foreign Investment and Export Manufacturing','1980s–2001',1980,2001,'world-event-15-1',['9.4'],['ECN','GOV'],['Causation']],
  ['apwh-u9-guangzhou-supply-chain-labor-environmental-costs','15',3,'Supply-Chain Expansion, Labor, and Environmental Costs','2001–2010s',2001,2019,'world-event-15-1',['9.3','9.4','9.9'],['ECN','SIO','ENV'],['Causation','CCOT']],
  ['apwh-u9-ciudad-juarez-border-industrialization','65',1,'Border Industrialization before NAFTA','1965–1993',1965,1993,'world-event-65-0',['9.4'],['ECN','GOV'],['Contextualization']],
  ['apwh-u9-ciudad-juarez-nafta-maquiladora-expansion','65',2,'NAFTA and Maquiladora Expansion','1994–2000s',1994,2009,'world-event-65-0',['9.4'],['ECN','GOV'],['Causation']],
  ['apwh-u9-ciudad-juarez-employment-gender-labor-environment','65',3,'Employment, Gender, Labor, and Environmental Tradeoffs','1990s–2010s',1990,2019,'world-event-65-0',['9.3','9.4','9.9'],['ECN','SIO','ENV'],['Comparison','CCOT']],
  ['apwh-u9-beijing-market-reform-political-control','5',1,'Market Reform without Political Liberalization','1978–1989',1978,1989,'world-event-5-13',['9.4','9.5'],['ECN','GOV'],['Contextualization','Causation']],
  ['apwh-u9-beijing-tiananmen-protest-repression','5',2,'Tiananmen Protest and State Repression','1989',1989,1989,'world-event-5-13',['9.5'],['GOV','SIO'],['Causation']],
  ['apwh-u9-beijing-wto-integration-information-control','5',3,'WTO Integration and Controlled Information','2001–2010s',2001,2019,'world-event-5-13',['9.4','9.5','9.9'],['GOV','ECN','TEC'],['Causation','CCOT']],
  ['apwh-u9-washington-bretton-woods-financial-institutions','54',1,'Bretton Woods and Postwar Financial Institutions','1944–1945',1944,1945,'world-event-54-5',['9.8'],['GOV','ECN'],['Contextualization']],
  ['apwh-u9-washington-development-lending-conditionality','54',2,'Development Lending and Policy Conditionality','1950s–2000s',1950,2009,'world-event-54-5',['9.4','9.8'],['ECN','GOV'],['Causation']],
  ['apwh-u9-washington-institutional-power-benefits-criticism','54',3,'Institutional Power, Development Claims, and Criticism','1990s–2010s',1990,2019,'world-event-54-5',['9.7','9.8','9.9'],['GOV','ECN'],['Causation','Comparison']],
  ['apwh-u9-seattle-wto-expansion-rulemaking-criticism','112',1,'WTO Expansion and Rule-Making Criticism','1995–1999',1995,1999,'world-event-112-0',['9.7','9.8'],['GOV','ECN'],['Contextualization','Causation']],
  ['apwh-u9-seattle-coalition-protest-digital-organization','112',2,'Coalition Protest and Digital Organization','1999',1999,1999,'world-event-112-0',['9.1','9.5','9.7'],['GOV','SIO','TEC'],['Causation']],
  ['apwh-u9-seattle-fair-trade-labor-continuing-resistance','112',3,'Fair Trade, Labor Standards, and Continuing Resistance','2000s–2010s',2000,2019,'world-event-112-0',['9.5','9.7','9.9'],['GOV','ECN','SIO'],['CCOT','Comparison']],
  ['apwh-u9-paris-universal-rights-global-norm','24',1,'Universal Rights as a Global Norm','1948',1948,1948,'world-event-24-9',['9.5','9.8'],['GOV','CDI'],['Contextualization']],
  ['apwh-u9-paris-kyoto-burden-sharing-debate','24',2,'Kyoto-to-Paris Burden-Sharing Debate','1997–2015',1997,2015,'world-event-24-9',['9.3','9.8'],['ENV','GOV'],['Causation','Comparison']],
  ['apwh-u9-paris-voluntary-climate-governance-limits','24',3,'Paris Agreement and the Limits of Voluntary Governance','2015–2019',2015,2019,'world-event-24-9',['9.3','9.8','9.9'],['ENV','GOV'],['Causation','CCOT']],
  ['apwh-u9-geneva-vaccination-smallpox-eradication','34',1,'Vaccination Networks and Smallpox Eradication','1967–1980',1967,1980,'world-event-34-2',['9.2','9.8'],['TEC','GOV'],['Contextualization','Causation']],
  ['apwh-u9-geneva-hiv-treatment-unequal-access','34',2,'HIV/AIDS Treatment and Unequal Access','1980s–2000s',1980,2009,'world-event-34-2',['9.2','9.9'],['TEC','SIO'],['Causation','Comparison']],
  ['apwh-u9-geneva-polio-ebola-coordination-limits','34',3,'Polio, Ebola, and the Limits of Health Coordination','1988–2010s',1988,2019,'world-event-34-2',['9.2','9.8','9.9'],['TEC','GOV'],['Causation','CCOT']],
  ['apwh-u9-seoul-state-supported-cultural-industries','110',1,'State Support for Cultural Industries','1990s–2000s',1990,2009,'world-event-110-1',['9.4','9.6'],['CDI','ECN','GOV'],['Contextualization','Causation']],
  ['apwh-u9-seoul-digital-platforms-transnational-audiences','110',2,'Digital Platforms and Transnational Audiences','2000s–2010s',2000,2019,'world-event-110-1',['9.1','9.6'],['CDI','TEC','ECN'],['Causation']],
  ['apwh-u9-seoul-hybrid-culture-exports-soft-power','110',3,'Hybrid Culture, Exports, and Soft Power','2000s–2010s',2000,2019,'world-event-110-1',['9.6','9.9'],['CDI','ECN'],['Comparison','CCOT']],
];
const L=topics=>`AMSCO AP World History, Unit 9, ${topics.length===1?'Topic':'Topics'} ${topics.length===1?topics[0]:topics.length===2?topics.join(' and '):`${topics.slice(0,-1).join(', ')}, and ${topics.at(-1)}`}`;
const P=(id,summary,significance,person,role,term,explanation,evidence,examConnection,locator)=>({id,summary,significance,keyPeople:[{name:person,role}],keyTerms:[{term,explanation}],evidence,examConnection,source:{id:'amsco-apwh-u9',locator}});
const expectedContent=[
P('apwh-u9-amritsar-high-yield-seeds-input-package','High-yield wheat and rice varieties increased harvest potential only when farmers could combine them with irrigation, fertilizer, credit, land, and mechanization.','Amritsar–Punjab is a representative anchor for Green Revolution change, and seeds alone did not produce equal gains because complementary inputs were distributed unevenly.','Indian agricultural officials and Punjab farmers','Distributed new varieties and made choices about irrigation, fertilizer, credit, land, and machinery.','Green Revolution','The spread of high-yield crop varieties together with the inputs and institutions needed to raise agricultural output.',['High-yield wheat varieties spread widely in Punjab during the late 1960s.','Tube wells, fertilizer purchases, rural credit, and tractors helped farmers realize higher yields.'],'Explain causation by linking new seed varieties to the irrigation, fertilizer, credit, land, and mechanization that made them productive.',L(['9.1','9.3'])),
P('apwh-u9-amritsar-unequal-access-land-consolidation','Farmers with larger holdings and better access to water, loans, fertilizer, and machinery often adopted the new package faster than smallholders.','Unequal input access could widen rural inequality, encourage land consolidation, and reduce demand for some forms of agricultural labor.','Punjab landowners, smallholders, and agricultural laborers','Experienced different costs and benefits from capital-intensive agricultural change.','land consolidation','The concentration of farmland into fewer or larger holdings through purchase, debt, or displacement.',['Larger landowners were generally better positioned to obtain formal credit and purchase machinery.','Mechanized pumping and harvesting raised capital costs and changed demand for hired labor.'],'Compare how land, credit, irrigation, and machinery shaped unequal gains for large landowners, smallholders, and laborers.',L(['9.3','9.4'])),
P('apwh-u9-amritsar-food-population-environmental-costs','Higher grain output supported food security and population growth, while intensive irrigation and chemical inputs created long-term water and soil pressures.','The case joins a major increase in food supply to uneven social gains and environmental costs rather than treating agricultural technology as an unqualified success.','Punjab farming communities and environmental officials','Managed expanding food production alongside falling water tables and soil stress.','groundwater depletion','The decline of underground water reserves when pumping exceeds natural recharge.',['India moved from chronic grain shortages toward much greater wheat and rice output after the Green Revolution.','Intensive groundwater pumping and fertilizer use contributed to falling water tables and soil degradation in Punjab.'],'Trace continuity and change by weighing increased food supply and population support against water, soil, and inequality costs.',L(['9.3','9.9'])),
P('apwh-u9-san-francisco-public-research-digital-infrastructure','Public universities, defense research, and government procurement supported semiconductor and computing networks that private firms later commercialized.','San Francisco is a representative anchor for a wider Bay Area ecosystem in which public investment helped create digital infrastructure and skilled labor.','Public research agencies, universities, and technology firms','Funded research, trained workers, and commercialized semiconductor and computing applications.','semiconductor','A material and electronic component used to control electrical signals in modern computing devices.',['Federal defense and research spending supported electronics laboratories and university work in California.','Integrated-circuit firms and a skilled workforce clustered around the wider San Francisco Bay Area.'],'Contextualize private innovation by identifying the public research, procurement, education, and infrastructure that supported it.',L(['9.1'])),
P('apwh-u9-san-francisco-computing-internet-information-costs','Advances in semiconductors, personal computing, and internet networks sharply lowered information costs for storing, processing, and transmitting data.','Cheaper communication accelerated market integration across distance, while the Bay Area was one commercialization hub among many contributors to global networks.','Computer engineers, public network researchers, and entrepreneurs','Improved computing capacity and expanded interoperable digital networks.','internet','A global network of interconnected computer networks that exchange data through common protocols.',['Microprocessor costs fell while computing power increased during the late twentieth century.','Publicly funded networking research and commercial services connected users across institutions and countries.'],'Explain how computing and internet infrastructure reduced information costs without assigning a global network to one city.',L(['9.1','9.4'])),
P('apwh-u9-san-francisco-knowledge-economy-distributed-production','Digital firms concentrated design, software, finance, and knowledge work while distributed production placed manufacturing and support functions in global supply chains.','The knowledge economy created high-value work and rapid coordination but also widened regional and occupational inequality.','Technology firms and global supply-chain workers','Coordinated knowledge-intensive services with production performed across multiple countries.','knowledge economy','An economy in which information, expertise, research, and intellectual property are major sources of value.',['Bay Area firms retained design and software functions while contracting hardware production to factories abroad.','Digital platforms allowed teams and suppliers to coordinate production across long distances.'],'Trace how lower information costs changed the location of knowledge work and distributed production while preserving uneven gains.',L(['9.4','9.9'])),
P('apwh-u9-guangzhou-market-reform-special-economic-zones','Deng-era leaders authorized market reforms and special economic zones in coastal Guangdong to test investment, trade, and production incentives.','Export growth followed a state choice about law, infrastructure, and location rather than an automatic technology effect.','Deng Xiaoping and Chinese state officials','Authorized reform experiments and coastal zones while retaining Communist Party political control.','special economic zone','A designated area where a government applies distinct trade, investment, tax, or regulatory policies.',['China began major market-oriented reforms after 1978 under Deng Xiaoping.','Shenzhen and other Guangdong zones received preferential policies and infrastructure near export routes.'],'Explain why special economic zone growth depended on state choices, geography, and investment rules rather than technology alone.',L(['9.4'])),
P('apwh-u9-guangzhou-foreign-investment-export-manufacturing','Special policies attracted foreign direct investment and linked Guangdong factories to export markets and transnational production networks.','Foreign capital, abundant labor, state infrastructure, and port access combined to expand export manufacturing.','Chinese local governments and foreign investors','Built factories, infrastructure, and supplier networks for export-oriented production.','foreign direct investment','Investment by an entity based in one country that establishes or controls productive assets in another.',['Overseas Chinese and multinational investors financed factories across the Pearl River Delta.','Manufactured exports expanded through ports serving Guangzhou, Shenzhen, and Hong Kong.'],'Build a multicausal argument connecting foreign investment, labor, infrastructure, policy incentives, and export access.',L(['9.4'])),
P('apwh-u9-guangzhou-supply-chain-labor-environmental-costs','After China joined the WTO, firms expanded supply-chain production in the Pearl River Delta and drew migrant labor into export factories.','Supply relocation increased jobs and output while producing demanding labor regimes, pollution, and uneven regional gains.','Migrant workers, factory managers, and environmental regulators','Produced export goods and contested working conditions and environmental damage.','supply-chain relocation','The movement of production stages to new regions to lower costs or reach suppliers and markets.',['China entered the World Trade Organization in 2001 and manufactured exports rose rapidly.','Pearl River Delta factories relied on migrant labor and generated significant air and water pollution.'],'Trace continuity and change after WTO entry by weighing supply-chain growth against labor and environmental costs.',L(['9.3','9.4','9.9'])),
P('apwh-u9-ciudad-juarez-border-industrialization','Mexico created the Border Industrialization Program before NAFTA to encourage foreign-owned assembly plants along the United States border.','The 1965 program established the maquiladora model, so border industrialization cannot be attributed to NAFTA alone.','Mexican officials and border manufacturers','Created tariff and investment arrangements for export assembly along the northern border.','Border Industrialization Program','Mexico’s program promoting export-oriented assembly plants in its northern border region.',['Mexico launched the Border Industrialization Program in 1965.','Ciudad Juárez plants imported components, assembled goods, and re-exported finished products.'],'Contextualize NAFTA by distinguishing the earlier Border Industrialization Program from later free-trade expansion.',L(['9.4'])),
P('apwh-u9-ciudad-juarez-nafta-maquiladora-expansion','NAFTA reduced trade barriers and encouraged cross-border production networks, accelerating maquiladora expansion around Ciudad Juárez.','The agreement enlarged an existing assembly system by making components, capital, and finished goods easier to move across North America.','Mexican, United States, and Canadian trade officials','Negotiated rules that increased regional trade and investment integration.','NAFTA','The 1994 agreement reducing many trade and investment barriers among Mexico, the United States, and Canada.',['NAFTA took effect in 1994 among Mexico, the United States, and Canada.','Maquiladora employment and export production expanded along the northern Mexican border during the 1990s.'],'Explain how NAFTA accelerated rather than originated maquiladora development.',L(['9.4'])),
P('apwh-u9-ciudad-juarez-employment-gender-labor-environment','Maquiladora employment expanded, especially for women and migrants, while workers faced low pay, insecurity, gendered risks, and industrial pollution.','Export manufacturing shows that job creation could coexist with labor vulnerability, gender inequality, and environmental damage.','Maquiladora workers and labor organizers','Produced export goods and organized around wages, safety, gender violence, and workplace rights.','maquiladora','An export-oriented factory in Mexico that imports components for assembly and re-exports finished goods.',['Women made up a large share of early maquiladora workforces in Ciudad Juárez.','Rapid industrial growth strained water, waste, housing, and pollution controls along the border.'],'Compare employment gains with gender, labor, and pollution tradeoffs in maquiladora production.',L(['9.3','9.4','9.9'])),
P('apwh-u9-beijing-market-reform-political-control','Chinese leaders expanded market incentives and foreign trade after 1978 while preserving one-party political authority.','Market reform did not automatically bring political liberalization, demonstrating that economic change and political control could develop together.','Deng Xiaoping and the Chinese Communist Party','Directed market-oriented reforms while maintaining one-party rule.','reform and opening','China’s post-1978 program of market incentives, foreign investment, and wider engagement with world trade.',['Household responsibility reforms and township enterprises expanded market activity after 1978.','The Chinese Communist Party retained control of national political institutions throughout the reform era.'],'Contextualize Chinese globalization by separating market reform from political liberalization.',L(['9.4','9.5'])),
P('apwh-u9-beijing-tiananmen-protest-repression','Students and other citizens demanded political change in 1989, and the state used military force to end the Tiananmen Square demonstrations.','The repression showed that leaders chose coercive political control even as economic reform continued.','Student demonstrators and Chinese state leaders','Organized demands for reform and ordered or carried out the suppression of protests.','Tiananmen Square protests','The 1989 Beijing demonstrations for political reform that ended in a violent military crackdown.',['Large demonstrations occupied Tiananmen Square during the spring of 1989.','Chinese troops and armored vehicles cleared central Beijing on 3–4 June 1989.'],'Explain how state repression preserved political control without treating the outcome as an automatic result of market reform.',L(['9.5'])),
P('apwh-u9-beijing-wto-integration-information-control','WTO membership deepened China’s trade integration while the state expanded censorship, surveillance, and platform controls over digital information.','Economic integration did not cause democratization; leaders combined world-market participation with information control.','Chinese trade officials and internet regulators','Managed WTO integration while restricting political information and digital communication.','Great Firewall','The laws, filtering systems, and platform controls used by the Chinese state to regulate internet access and content.',['China joined the World Trade Organization in 2001.','Authorities blocked websites, filtered searches, and required domestic platforms to police online content.'],'Trace deeper WTO integration alongside continued one-party rule and evolving information control.',L(['9.4','9.5','9.9'])),
P('apwh-u9-washington-bretton-woods-financial-institutions','The Bretton Woods conference designed the IMF and World Bank framework for postwar monetary stability and reconstruction; the WTO emerged later from a separate trade system.','Washington, D.C. is a headquarters anchor, and the World Bank, IMF, and WTO were distinct institutions with different origins and functions.','Bretton Woods delegates and postwar governments','Created multilateral monetary and development institutions after World War II.','Bretton Woods institutions','The International Monetary Fund and World Bank organizations established from the 1944 Bretton Woods agreements.',['Delegates from forty-four Allied countries met at Bretton Woods in 1944.','The IMF addressed monetary stability, while the World Bank initially financed reconstruction and development.'],'Contextualize financial governance by distinguishing the IMF and World Bank from the later WTO trade regime.',L(['9.8'])),
P('apwh-u9-washington-development-lending-conditionality','The World Bank financed development projects, while the IMF offered balance-of-payments support that often required borrowers to adopt policy conditions.','Lending could fund infrastructure or stabilize currencies, but conditionality could also reduce policy autonomy and impose social costs.','World Bank and IMF officials with borrowing governments','Negotiated development lending, stabilization programs, and attached policy conditions.','conditionality','Economic or administrative policy changes that a lending institution requires a borrower to adopt.',['World Bank loans financed dams, roads, schools, and other development projects.','IMF programs often required fiscal restraint, currency changes, or market-oriented reforms.'],'Explain how lending and conditionality produced both claimed development gains and contested social costs.',L(['9.4','9.8'])),
P('apwh-u9-washington-institutional-power-benefits-criticism','Supporters credited global institutions with development finance and trade rules, while critics challenged unequal voting power and policy influence.','Institutional outcomes reflected cooperation and power imbalances because wealthy states held disproportionate votes and bargaining leverage.','Member governments, institutional officials, and civil-society critics','Debated development benefits, governance rules, voting power, and criticism of accountability.','weighted voting','A system in which members have different vote shares, often connected to financial contributions.',['United States voting power has been especially large in the IMF and World Bank.','Critics linked some adjustment programs to public-spending cuts and protested global economic rules.'],'Compare claimed gains in finance and rule making with criticism of voting power, conditionality, and unequal influence.',L(['9.7','9.8','9.9'])),
P('apwh-u9-seattle-wto-expansion-rulemaking-criticism','The WTO expanded a rules-based trade system, and its 1999 Seattle ministerial focused criticism on transparency, labor, and environmental consequences.','Resistance targeted how global trade rules were made and whose interests they served, not simply international exchange.','WTO delegates and globalization critics','Debated trade negotiations, institutional authority, and public accountability.','WTO ministerial conference','A meeting of World Trade Organization members that makes major decisions about negotiations and trade rules.',['The WTO began operating in 1995 as the successor to the GATT trade framework.','Its Seattle ministerial opened in November 1999 amid disputes and mass protest.'],'Contextualize Seattle by connecting WTO expansion to criticism of rule making, labor, and the environment.',L(['9.7','9.8'])),
P('apwh-u9-seattle-coalition-protest-digital-organization','Labor unions, environmentalists, students, and human-rights advocates built a coalition and used internet communication to organize protest.','Internet networks lowered organizing costs, while coalition building and on-the-ground action made Seattle mobilization possible.','Labor, environmental, student, and human-rights organizers','Coordinated demonstrations and public arguments across distinct movements.','digital mobilization','The use of networked communication to coordinate collective action, share information, and recruit participants.',['Organizers used email lists and websites to circulate plans before the 1999 ministerial.','Tens of thousands of protesters disrupted access to meeting sites in central Seattle.'],'Explain how internet organizing and a labor-environment coalition contributed to protest without reducing mobilization to technology.',L(['9.1','9.5','9.7'])),
P('apwh-u9-seattle-fair-trade-labor-continuing-resistance','After Seattle, activists promoted fair trade, labor standards, environmental safeguards, and continued resistance at later global summits.','The movement continued criticism of unequal globalization while shifting among protest, consumer campaigns, advocacy, and reform.','Fair-trade advocates and transnational labor networks','Pressed for labor protections, environmental standards, and accountable trade rules.','fair trade','An approach to exchange seeking better prices, labor conditions, environmental practices, and producer bargaining power.',['Fair-trade certification linked consumer purchases to standards for producers and workers.','Global justice activists continued resistance at later WTO, IMF, World Bank, and Group of Eight meetings.'],'Trace continuity and change from the Seattle coalition to later fair trade, labor, and global-justice campaigns.',L(['9.5','9.7','9.9'])),
P('apwh-u9-paris-universal-rights-global-norm','The UN adopted the Universal Declaration of Human Rights in Paris, articulating rights as a global standard without automatic enforcement.','Paris is a representative diplomacy anchor for a broader human rights framework negotiated by delegates from many societies.','Eleanor Roosevelt and United Nations delegates','Drafted and negotiated universal civil, political, social, and economic rights.','Universal Declaration of Human Rights','The 1948 United Nations declaration setting a common global standard for human rights.',['The UN General Assembly adopted the declaration in Paris on 10 December 1948.','The declaration included civil and political rights as well as social and economic rights.'],'Contextualize human rights governance by distinguishing a global norm from a binding enforcement mechanism.',L(['9.5','9.8'])),
P('apwh-u9-paris-kyoto-burden-sharing-debate','Climate negotiations from Kyoto to Paris struggled over how industrialized and developing states should divide responsibility for emissions reductions.','Burden sharing remained contested because historical emissions, current emissions, development needs, and sovereignty supported different claims.','Climate negotiators from industrialized and developing states','Debated differentiated responsibility, targets, finance, and national sovereignty.','common but differentiated responsibilities','The principle that all states share environmental duties but have different obligations because of capacity and historical contribution.',['The 1997 Kyoto Protocol assigned binding targets mainly to industrialized countries.','Negotiations toward Paris sought wider participation through nationally designed commitments.'],'Compare Kyoto and Paris approaches to burden sharing, sovereignty, participation, and enforcement.',L(['9.3','9.8'])),
P('apwh-u9-paris-voluntary-climate-governance-limits','The Paris Agreement used nationally determined contributions, reporting, and review to coordinate climate action while leaving target levels nationally chosen.','Broad participation increased, but voluntary commitments and weak enforcement limited guaranteed emissions reductions.','National climate negotiators and UN climate officials','Submitted, reviewed, and revised national climate commitments under a common framework.','nationally determined contribution','A climate-action target and plan that each party defines for itself under the Paris Agreement.',['Nearly every state adopted the Paris Agreement in 2015.','The agreement required reporting and renewed pledges but no single enforceable target for every country.'],'Evaluate broad participation and transparency against sovereignty and enforcement limits in the Paris Agreement.',L(['9.3','9.8','9.9'])),
P('apwh-u9-geneva-vaccination-smallpox-eradication','The WHO coordinated surveillance, vaccination, and assistance that helped eradicate smallpox worldwide.','Geneva is a coordination anchor for a campaign whose success depended on national health workers, local participation, and targeted vaccination.','WHO officials and national vaccination teams','Coordinated surveillance, vaccine delivery, case tracing, and containment across borders.','ring vaccination','The strategy of vaccinating contacts around detected cases to interrupt disease transmission.',['The WHO intensified the global smallpox eradication campaign in 1967.','The World Health Assembly declared smallpox eradicated in 1980.'],'Explain how WHO coordination, vaccination, surveillance, and local implementation combined to eradicate smallpox.',L(['9.2','9.8'])),
P('apwh-u9-geneva-hiv-treatment-unequal-access','Researchers and health agencies expanded antiretroviral treatment for HIV, but patents, prices, infrastructure, and stigma produced unequal access.','Medical innovation did not distribute itself evenly; resources, state capacity, activism, and policy choices shaped treatment access.','People living with HIV, treatment activists, and health agencies','Demanded affordable medicines and organized prevention and treatment programs.','antiretroviral therapy','Drug combinations that suppress HIV replication and allow many patients to live longer lives.',['Combination antiretroviral therapy became effective in the mid-1990s.','Generic drugs and international financing later expanded HIV treatment in many lower-income countries.'],'Compare effective HIV treatment with unequal access caused by price, patents, infrastructure, stigma, and resources.',L(['9.2','9.9'])),
P('apwh-u9-geneva-polio-ebola-coordination-limits','WHO-led programs coordinated polio vaccination and Ebola response, but weak surveillance, distrust, conflict, state capacity, and resources constrained implementation.','Global cooperation could mobilize expertise without eliminating the need for capable states and trusted local health systems.','WHO responders, health ministries, and community workers','Coordinated surveillance, vaccination, treatment, and public communication during disease campaigns.','disease surveillance','The systematic collection and analysis of health data used to detect cases and guide action.',['The Global Polio Eradication Initiative began in 1988 and reduced cases dramatically.','The 2014–2016 West African Ebola epidemic exposed shortages in surveillance, clinics, staff, and resources.'],'Trace why polio and Ebola coordination remained limited by surveillance, state capacity, trust, conflict, and resources.',L(['9.2','9.8','9.9'])),
P('apwh-u9-seoul-state-supported-cultural-industries','South Korean governments treated film, television, music, and digital media as strategic cultural industries and supported training, infrastructure, and exports.','Seoul is a representative anchor for a national strategy in which state support and private creativity interacted.','South Korean cultural agencies and media firms','Invested in production capacity, creative training, and export promotion.','Hallyu','The transnational popularity of South Korean popular culture, often called the Korean Wave.',['South Korea expanded cultural-industry policy and media investment after the 1990s.','Television dramas, film, and popular music became important cultural exports.'],'Contextualize cultural industries by linking state support, private firms, creative labor, and changing markets.',L(['9.4','9.6'])),
P('apwh-u9-seoul-digital-platforms-transnational-audiences','Broadband networks, streaming sites, social media, and fan communities allowed Korean music and drama to reach transnational audiences rapidly.','Digital distribution lowered barriers, while translation, recommendation systems, and organized fans actively built audiences.','Korean media producers and transnational fan communities','Distributed, translated, promoted, and discussed cultural products through digital platforms.','digital distribution','The circulation of media through networked platforms rather than only physical copies or broadcast channels.',['South Korea developed high levels of broadband access and digital-media use.','Online video, streaming, and social platforms carried Korean music and drama across continents.'],'Explain how digital platforms and fan networks changed the scale and speed of transnational audiences.',L(['9.1','9.6'])),
P('apwh-u9-seoul-hybrid-culture-exports-soft-power','Korean producers combined local language and themes with global genres, production styles, and marketing to create hybrid culture exports.','Seoul is a representative anchor for soft power, and globalization was not synonymous with Americanization.','Korean artists, producers, and cultural diplomats','Created hybrid media exports that influenced foreign audiences and national image.','soft power','The ability to attract and influence others through culture, values, and reputation rather than coercion.',['K-pop blended Korean lyrics and performance systems with hip-hop, electronic, and other transnational styles.','The South Korean state used cultural exports in tourism and public-diplomacy campaigns.'],'Compare cultural borrowing and local adaptation to show how hybrid exports generated economic value and soft power.',L(['9.6','9.9'])),
];
const localCausalPairs=[...expectedLocations.keys()].flatMap(location=>{
  const local=expectedManifest.filter(record=>record[1]===location).sort((a,b)=>a[2]-b[2]);
  return [[local[0][0],local[1][0]],[local[1][0],local[2][0]]];
});
const crossLocationCausalPairs=[
  ['apwh-u9-san-francisco-computing-internet-information-costs','apwh-u9-seoul-digital-platforms-transnational-audiences'],
  ['apwh-u9-guangzhou-foreign-investment-export-manufacturing','apwh-u9-beijing-wto-integration-information-control'],
  ['apwh-u9-ciudad-juarez-employment-gender-labor-environment','apwh-u9-seattle-coalition-protest-digital-organization'],
  ['apwh-u9-washington-development-lending-conditionality','apwh-u9-seattle-wto-expansion-rulemaking-criticism'],
];
const expectedCausalNotes={
  'apwh-u9-amritsar-high-yield-seeds-input-package|apwh-u9-amritsar-unequal-access-land-consolidation':'High-yield varieties required irrigation, fertilizer, credit, land, and machinery, so better-capitalized farmers adopted sooner while smallholders and laborers made choices within unequal constraints.',
  'apwh-u9-amritsar-unequal-access-land-consolidation|apwh-u9-amritsar-food-population-environmental-costs':'Unequal access and mechanization encouraged land consolidation and changed labor demand, while farming communities and officials expanded food output and confronted groundwater and soil costs.',
  'apwh-u9-san-francisco-public-research-digital-infrastructure|apwh-u9-san-francisco-computing-internet-information-costs':'Public research funding, university training, and procurement created infrastructure and expertise that engineers and entrepreneurs used to commercialize computing and expand interoperable networks.',
  'apwh-u9-san-francisco-computing-internet-information-costs|apwh-u9-san-francisco-knowledge-economy-distributed-production':'Lower computing and communication costs let firms coordinate design, software, services, and production across distance, while firms and workers shaped how uneven gains were distributed.',
  'apwh-u9-guangzhou-market-reform-special-economic-zones|apwh-u9-guangzhou-foreign-investment-export-manufacturing':'Chinese officials designed special-zone incentives, infrastructure, and investment rules that foreign investors and local governments used to build export factories and supplier networks.',
  'apwh-u9-guangzhou-foreign-investment-export-manufacturing|apwh-u9-guangzhou-supply-chain-labor-environmental-costs':'Foreign-financed export capacity and WTO access expanded supply-chain production, while migrant workers, factory managers, and regulators contested working conditions and pollution.',
  'apwh-u9-ciudad-juarez-border-industrialization|apwh-u9-ciudad-juarez-nafta-maquiladora-expansion':'Mexico’s earlier border program created an assembly base that NAFTA negotiators enlarged by reducing trade barriers, while firms chose to expand cross-border production networks.',
  'apwh-u9-ciudad-juarez-nafta-maquiladora-expansion|apwh-u9-ciudad-juarez-employment-gender-labor-environment':'Maquiladora expansion increased employment and reorganized gendered labor while workers and border communities challenged wages, safety conditions, and industrial pollution.',
  'apwh-u9-beijing-market-reform-political-control|apwh-u9-beijing-tiananmen-protest-repression':'Market reform without political liberalization sharpened demands for change that students and workers organized publicly, while party leaders chose military repression to preserve one-party rule.',
  'apwh-u9-beijing-tiananmen-protest-repression|apwh-u9-beijing-wto-integration-information-control':'After suppressing political challenge, party leaders retained one-party control while choosing WTO integration and digital restrictions that firms and users adapted to and contested.',
  'apwh-u9-washington-bretton-woods-financial-institutions|apwh-u9-washington-development-lending-conditionality':'Postwar agreements created lending capacity and unequal voting rules that institution officials and borrowing governments used and negotiated through development loans and policy conditions.',
  'apwh-u9-washington-development-lending-conditionality|apwh-u9-washington-institutional-power-benefits-criticism':'Conditional lending and weighted voting distributed development benefits, policy constraints, and risks unevenly, prompting borrower governments and civil-society groups to criticize institutional power.',
  'apwh-u9-seattle-wto-expansion-rulemaking-criticism|apwh-u9-seattle-coalition-protest-digital-organization':'Concerns about WTO rules on labor, environment, sovereignty, and transparency gave diverse organizations shared targets, while organizers used digital networks to coordinate summit protest.',
  'apwh-u9-seattle-coalition-protest-digital-organization|apwh-u9-seattle-fair-trade-labor-continuing-resistance':'Coalition networks and summit experience helped labor, environmental, and fair-trade advocates sustain consumer campaigns, institutional reform efforts, and later global-justice mobilization.',
  'apwh-u9-paris-universal-rights-global-norm|apwh-u9-paris-kyoto-burden-sharing-debate':'The universal-rights framework supplied language for transnational responsibility, while states negotiated climate burdens through competing claims about sovereignty, capacity, and historical emissions.',
  'apwh-u9-paris-kyoto-burden-sharing-debate|apwh-u9-paris-voluntary-climate-governance-limits':'Conflict over Kyoto’s differentiated targets and participation led negotiators to broaden participation through nationally determined contributions, while states retained authority to set ambition.',
  'apwh-u9-geneva-vaccination-smallpox-eradication|apwh-u9-geneva-hiv-treatment-unequal-access':'Smallpox campaigns strengthened WHO coordination and international health networks that agencies and activists later used to expand HIV treatment, while patents, prices, and state capacity kept access unequal.',
  'apwh-u9-geneva-hiv-treatment-unequal-access|apwh-u9-geneva-polio-ebola-coordination-limits':'HIV access struggles expanded global health financing, community-based delivery, and medicine-access advocacy that polio and Ebola teams adapted while confronting surveillance, conflict, and trust barriers.',
  'apwh-u9-seoul-state-supported-cultural-industries|apwh-u9-seoul-digital-platforms-transnational-audiences':'State investment and private creativity built media capacity and digital infrastructure that producers, platforms, translators, and fan communities used to reach audiences across borders.',
  'apwh-u9-seoul-digital-platforms-transnational-audiences|apwh-u9-seoul-hybrid-culture-exports-soft-power':'Transnational platforms and active fan communities rewarded hybrid cultural production, while Korean creators and diplomats converted export popularity into economic value and soft power.',
  'apwh-u9-san-francisco-computing-internet-information-costs|apwh-u9-seoul-digital-platforms-transnational-audiences':'Lower information costs and interoperable networks enabled global platform distribution, while Korean producers, translators, and fan communities actively built transnational audiences.',
  'apwh-u9-guangzhou-foreign-investment-export-manufacturing|apwh-u9-beijing-wto-integration-information-control':'Export growth and foreign investment gave Chinese leaders incentives to pursue WTO accession, while party officials coupled deeper market integration with continuing information control.',
  'apwh-u9-ciudad-juarez-employment-gender-labor-environment|apwh-u9-seattle-coalition-protest-digital-organization':'Labor, gender, and environmental disputes in export zones supplied issues for transnational advocacy, while Seattle organizers chose to unite labor, environmental, and other movements.',
  'apwh-u9-washington-development-lending-conditionality|apwh-u9-seattle-wto-expansion-rulemaking-criticism':'Controversies over lending conditionality broadened demands for accountability in global economic governance, while WTO members and Seattle critics pursued competing rule-making priorities.',
};
const expectedRelatedPairs=[
  ['apwh-u9-amritsar-unequal-access-land-consolidation','apwh-u9-guangzhou-supply-chain-labor-environmental-costs','Compare unequal gains and environmental costs: Punjab’s input-intensive agriculture encouraged land consolidation and changed farm labor, while Guangzhou’s export manufacturing relied on migrant factory labor and produced industrial pollution.'],
  ['apwh-u9-guangzhou-foreign-investment-export-manufacturing','apwh-u9-ciudad-juarez-nafta-maquiladora-expansion','Compare routes to export growth: Chinese leaders unilaterally authorized market reforms and special zones, while NAFTA negotiators changed rules among three states and expanded an older maquiladora system.'],
  ['apwh-u9-beijing-tiananmen-protest-repression','apwh-u9-seattle-coalition-protest-digital-organization','Compare political contestation: China’s one-party state used military repression against domestic protesters, while Seattle’s pluralist coalition challenged a global summit within an electoral political system.'],
  ['apwh-u9-washington-institutional-power-benefits-criticism','apwh-u9-paris-voluntary-climate-governance-limits','Compare enforcement and power: financial institutions use weighted voting and lending conditionality, while global rights and climate governance relies more on voluntary commitments, reporting, persuasion, and state cooperation.'],
  ['apwh-u9-geneva-polio-ebola-coordination-limits','apwh-u9-paris-voluntary-climate-governance-limits','Compare collective-action problems: targeted disease campaigns can coordinate surveillance and intervention around cases, while climate mitigation requires long-term economy-wide changes that states must sustain.'],
];
const expectedUnitCards={
  context:{id:'apwh-u9-context-post-cold-war-globalized-system',kind:'context',role:'Unit 9 Context Card',title:'From the End of the Cold War to a Globalized System',examSkills:['Contextualization','Causation'],summary:'The end of the Cold War removed a rival superpower system just as market reforms, trade agreements, container shipping, air travel, and digital communications accelerated the movement of goods, capital, information, and people. Institutions created after World War II gained wider reach, but newly integrated states entered with unequal bargaining power, infrastructure, debt, and access to technology.',prompt:'How did the end of the Cold War and falling transportation and information costs change the scale and rules of global interaction?',takeaways:['The collapse of the Soviet bloc widened participation in a predominantly market-oriented global economy.','Technology reduced the cost of connection without distributing the gains or risks equally.','Postwar institutions expanded their reach while retaining unequal voting power and limited enforcement.']},
  synthesis:{id:'apwh-u9-synthesis-regional-networks-planetary-interdependence',kind:'synthesis',role:'Unit 9 Synthesis Card',title:'From Regional Networks to Planetary Interdependence',examSkills:['CCOT','Causation'],summary:'Since c. 1200, exchange networks repeatedly widened as states, merchants, empires, industries, and institutions reduced the cost of moving goods, labor, capital, and ideas. By the late twentieth century those networks connected production, communication, health, culture, human rights, and the environment at planetary scale, but no world government acquired matching authority to distribute gains, enforce rules, or assign responsibility for shared costs.',prompt:'Across Units 1–9, how did expanding networks change who wrote the rules, captured the gains, and bore the costs of interdependence?',takeaways:['Technologies changed the speed and scale of exchange, while political institutions determined access and rules.','Expanding networks created recurring inequalities between centers, intermediaries, workers, and environments.','Global problems became harder to contain within states even though enforcement still depended on state cooperation.']},
};
const clone=value=>JSON.parse(JSON.stringify(value));
const replace=(search,replacement)=>{const code=source.replace(search,replacement);assert.notEqual(code,source,`fixture mutation: ${search}`);return code;};
const assertInvalid=(code,rule)=>assert.throws(()=>evaluate(code),error=>{assert.equal(error.name,'Error');assert.match(error.message,/Invalid Unit 9/);assert.match(error.message,rule);return true;});
const failLedger=rule=>{throw new Error(`Invalid Unit 9 source ledger: ${rule}`);};
const backslashRunBefore=(value,index)=>{let backslashes=0;for(let cursor=index-1;cursor>=0&&value[cursor]==='\\';cursor-=1)backslashes+=1;return backslashes;};
const parseMarkdownRowCells=row=>{
  if(!row.startsWith('|')||!row.endsWith('|')||backslashRunBefore(row,row.length-1)%2===1)failLedger('row must start and end with pipe delimiters');
  const cells=[];let cell='';
  for(let index=1;index<row.length;index+=1){const character=row[index];if(character!=='|'){cell+=character;continue;}const backslashes=backslashRunBefore(row,index);if(backslashes)cell=`${cell.slice(0,-backslashes)}${'\\'.repeat(Math.floor(backslashes/2))}`;if(backslashes%2===1){cell+='|';continue;}cells.push(cell.trim());cell='';}
  return cells;
};
const parseLedgerRows=candidate=>{
  if(!candidate.startsWith(ledgerIntroduction))failLedger('missing canonical introduction');
  const tablePrefix=`${ledgerIntroduction}\n\n${ledgerHeader}\n${ledgerSeparator}\n`;
  if(!candidate.startsWith(tablePrefix))failLedger('table header must immediately follow canonical introduction');
  const lines=candidate.split('\n'),headerIndex=ledgerIntroduction.split('\n').length+1,expectedIds=new Set(expectedLedgerRows.map(row=>row[0])),rows=[];let tableEnd=headerIndex+2;
  for(;tableEnd<lines.length;tableEnd+=1){const raw=lines[tableEnd];if(!raw)break;const cells=parseMarkdownRowCells(raw);if(cells.length!==5)failLedger('row must contain exactly five columns');if(!/^apwh-u9-[a-z0-9]+(?:-[a-z0-9]+)*$/.test(cells[0]))failLedger(`malformed Stable ID cell ${cells[0]}`);if(!expectedIds.has(cells[0]))failLedger(`unexpected Stable ID ${cells[0]}`);if(!/^world-event-\d+-\d+$/.test(cells[2]))failLedger(`malformed Main event cell ${cells[2]}`);if(/\b(?:p|pp)\.\s*\d+/i.test(cells[3]))failLedger('unverified page number');if(!/^AMSCO AP World History, Unit 9, Topics? 9\.[1-9]/.test(cells[3]))failLedger('vague source locator');if(!/project-authored (?:causal |comparison |)analysis/.test(cells[4]))failLedger('missing source-analysis distinction');rows.push(cells);}
  if(lines.slice(tableEnd).some(line=>line.trim()))failLedger('unexpected trailing content');
  const parsedOccurrences=new Map();for(const [id] of rows)parsedOccurrences.set(id,(parsedOccurrences.get(id)||0)+1);for(const match of candidate.matchAll(/apwh-u9-[A-Za-z0-9_-]*/g)){const id=match[0],remaining=parsedOccurrences.get(id)||0;if(!remaining)failLedger(`unparsed Stable ID occurrence ${id}`);parsedOccurrences.set(id,remaining-1);}
  if(rows.length!==expectedLedgerRows.length)failLedger(`expected exactly ${expectedLedgerRows.length} data rows`);
  for(let index=0;index<expectedLedgerRows.length;index+=1)if(JSON.stringify(rows[index])!==JSON.stringify(expectedLedgerRows[index]))failLedger(`row ${index+1} does not match the canonical record order and fields`);
  return rows;
};

test('publishes the exact immutable Unit 9 manifest and complete learner contract',()=>{
  assert.ok(source,`Expected ${moduleUrl.pathname} to exist`);const api=evaluate();
  assert.deepEqual(Object.keys(api),['unitId','unitNumber','connectionTimelineMode','locationNumbers','records','unitCards','compareRecords','getById','getByLocation','locationName','getUnitCard']);
  assert.equal(api.unitId,'u9');assert.equal(api.unitNumber,9);assert.equal(api.connectionTimelineMode,'main-event');
  assert.deepEqual(Array.from(api.locationNumbers),Array.from(expectedLocations.keys()));assert.equal(api.records.length,30);
  assert.deepEqual(clone(api.records.map(({id,locationNumber,sequence,title,dateLabel,startYear,endYear,mainEventKey,topicCodes,themeIds,examSkills})=>[id,locationNumber,sequence,title,dateLabel,startYear,endYear,mainEventKey,topicCodes,themeIds,examSkills])),expectedManifest);
  assert.deepEqual([...new Set(api.records.flatMap(record=>record.topicCodes))].sort(),['9.1','9.2','9.3','9.4','9.5','9.6','9.7','9.8','9.9']);
  for(const record of api.records){assert.deepEqual(Object.keys(record),['id','summary','significance','keyPeople','keyTerms','evidence','examConnection','source','locationNumber','sequence','title','dateLabel','startYear','endYear','mainEventKey','topicCodes','themeIds','examSkills','causeStudyPointIds','effectStudyPointIds','relatedStudyPointIds','connectionNotes']);assert.match(record.id,/^apwh-u9-[a-z0-9]+(?:-[a-z0-9]+)*$/);assert.ok(record.summary);assert.ok(record.significance);assert.ok(record.keyPeople.length);assert.ok(record.keyTerms.length);assert.equal(new Set(record.keyTerms.map(term=>term.term)).size,record.keyTerms.length);assert.ok(record.keyTerms.every(term=>term.explanation));assert.ok(record.evidence.length>=2);assert.match(record.examConnection,/^(Analyze|Build|Compare|Contextualize|Evaluate|Explain|Trace)\b/);assert.equal(record.source.id,'amsco-apwh-u9');assert.equal(record.source.locator,L(record.topicCodes));}
});

test('binds exactly three ordered records to each exact location and main event',()=>{
  const api=evaluate();for(const [number,name] of expectedLocations){assert.equal(api.locationName(number),name);const records=api.getByLocation(number);assert.equal(records.length,3);assert.deepEqual(Array.from(records,record=>record.sequence),[1,2,3]);assert.ok(records.every(record=>record.mainEventKey===expectedBindings.get(number)));}
});

test('locks the required Unit 9 content fixtures and historical boundaries',()=>{
  const api=evaluate(),text=id=>JSON.stringify(api.getById(id));
  const content=api.records.map(({id,summary,significance,keyPeople,keyTerms,evidence,examConnection,source})=>({id,summary,significance,keyPeople,keyTerms,evidence,examConnection,source}));
  assert.equal(content.length,expectedContent.length);
  for(let index=0;index<expectedContent.length;index+=1){const actual=content[index],expected=expectedContent[index];for(const field of ['id','summary','significance','keyPeople','keyTerms','evidence','examConnection','source'])assert.deepEqual(clone(actual[field]),expected[field],`${expected.id}: ${field}`);}
  const boundaries=[
    ['apwh-u9-amritsar-high-yield-seeds-input-package',['Amritsar–Punjab is a representative anchor','seeds alone did not produce equal gains','high-yield','irrigation','fertilizer','credit','land','mechanization']],
    ['apwh-u9-amritsar-food-population-environmental-costs',['food','population','water','soil']],
    ['apwh-u9-san-francisco-public-research-digital-infrastructure',['San Francisco is a representative anchor','public','semiconductor','comput']],
    ['apwh-u9-san-francisco-computing-internet-information-costs',['internet','information costs']],
    ['apwh-u9-san-francisco-knowledge-economy-distributed-production',['knowledge','distributed production']],
    ['apwh-u9-guangzhou-market-reform-special-economic-zones',['Deng','special economic zone','state choice']],
    ['apwh-u9-guangzhou-supply-chain-labor-environmental-costs',['supply','labor','environment']],
    ['apwh-u9-ciudad-juarez-border-industrialization',['Border Industrialization Program','before NAFTA']],
    ['apwh-u9-ciudad-juarez-employment-gender-labor-environment',['maquiladora','gender','labor','pollution']],
    ['apwh-u9-beijing-market-reform-political-control',['market reform','political liberalization']],
    ['apwh-u9-beijing-tiananmen-protest-repression',['Tiananmen','repression']],
    ['apwh-u9-beijing-wto-integration-information-control',['WTO','information control','did not cause democratization']],
    ['apwh-u9-washington-bretton-woods-financial-institutions',['Washington, D.C. is a headquarters anchor','the World Bank, IMF, and WTO were distinct institutions','Bretton Woods']],
    ['apwh-u9-washington-institutional-power-benefits-criticism',['voting power','criticism']],
    ['apwh-u9-seattle-coalition-protest-digital-organization',['coalition','internet','labor','environment']],
    ['apwh-u9-seattle-fair-trade-labor-continuing-resistance',['fair trade','resistance']],
    ['apwh-u9-paris-universal-rights-global-norm',['UN','human rights','representative diplomacy anchor']],
    ['apwh-u9-paris-kyoto-burden-sharing-debate',['Kyoto','burden sharing','sovereignty']],
    ['apwh-u9-paris-voluntary-climate-governance-limits',['Paris Agreement','nationally determined contribution','enforcement']],
    ['apwh-u9-geneva-vaccination-smallpox-eradication',['Geneva is a coordination anchor','WHO','vaccination','smallpox']],
    ['apwh-u9-geneva-hiv-treatment-unequal-access',['HIV','unequal access']],
    ['apwh-u9-geneva-polio-ebola-coordination-limits',['polio','Ebola','surveillance','state capacity','resources']],
    ['apwh-u9-seoul-state-supported-cultural-industries',['Seoul is a representative anchor','state support','cultural industr']],
    ['apwh-u9-seoul-digital-platforms-transnational-audiences',['digital','transnational audiences']],
    ['apwh-u9-seoul-hybrid-culture-exports-soft-power',['hybrid','export','soft power','globalization was not synonymous with Americanization']],
  ];
  for(const [id,phrases] of boundaries){const content=text(id);for(const phrase of phrases)assert.ok(content.toLowerCase().includes(phrase.toLowerCase()),`${id}: ${phrase}`);}
  const sanFrancisco=api.getByLocation('70').map(text).join(' ');assert.doesNotMatch(sanFrancisco,/internet (?:was )?invented (?:in|at)|World Wide Web (?:was )?invented (?:in|at)/i);
});

test('provides defensive lookups, comparator tie breakers, course-closing cards, and a locked global',()=>{
  const sandbox=evaluateSandbox(),api=sandbox.APWH_U9_LOCATION_STUDY,descriptor=Object.getOwnPropertyDescriptor(sandbox,'APWH_U9_LOCATION_STUDY');
  assert.deepEqual({enumerable:descriptor.enumerable,configurable:descriptor.configurable,writable:descriptor.writable},{enumerable:true,configurable:false,writable:false});
  assert.equal(api.getById(api.records[0].id),api.records[0]);assert.equal(api.getById('missing'),null);assert.equal(api.locationName('missing'),null);assert.deepEqual(Array.from(api.getByLocation('missing')),[]);
  const local=api.getByLocation('11');local.pop();assert.equal(api.getByLocation('11').length,3);
  const rows=[{sequence:2,startYear:1,endYear:1,id:'z'},{sequence:1,startYear:3,endYear:1,id:'z'},{sequence:1,startYear:2,endYear:3,id:'z'},{sequence:1,startYear:2,endYear:2,id:'z'},{sequence:1,startYear:2,endYear:2,id:'a'}];rows.sort(api.compareRecords);assert.deepEqual(rows.map(row=>[row.sequence,row.startYear,row.endYear,row.id]),[[1,2,2,'a'],[1,2,2,'z'],[1,2,3,'z'],[1,3,1,'z'],[2,1,1,'z']]);
  assert.deepEqual(clone(api.unitCards),expectedUnitCards);for(const [kind,card] of Object.entries(expectedUnitCards)){assert.equal(api.getUnitCard(kind),api.unitCards[kind]);assert.equal(api.getUnitCard(card.id),api.unitCards[kind]);}for(const key of ['missing','toString','constructor','__proto__'])assert.equal(api.getUnitCard(key),null);
  assert.throws(()=>evaluate(source,{APWH_U9_LOCATION_STUDY:{}}),/Invalid Unit 9 global APWH_U9_LOCATION_STUDY: refusing to overwrite existing value/);
});

test('deep freezes every published object and defensive array',()=>{
  const api=evaluate(),seen=new Set();const deep=value=>{if(value===null||typeof value!=='object'||seen.has(value))return;seen.add(value);assert.equal(Object.isFrozen(value),true);for(const key of Reflect.ownKeys(value))deep(value[key]);};deep(api);
  for(const record of api.records){assert.ok(Object.isFrozen(record.causeStudyPointIds));assert.ok(Object.isFrozen(record.effectStudyPointIds));assert.ok(Object.isFrozen(record.relatedStudyPointIds));assert.ok(Object.isFrozen(record.connectionNotes));}
});

test('publishes exactly twenty vertical and four cross-location causal links with reciprocal navigation',()=>{
  const api=evaluate(),byId=new Map(api.records.map(record=>[record.id,record])),expectedPairs=[...localCausalPairs,...crossLocationCausalPairs];
  const actualPairs=api.records.flatMap(record=>record.effectStudyPointIds.map(target=>[record.id,target]));
  const pairKey=([source,target])=>`${source}|${target}`;assert.equal(localCausalPairs.length,20);assert.equal(crossLocationCausalPairs.length,4);assert.deepEqual(clone(actualPairs.map(pairKey).sort()),expectedPairs.map(pairKey).sort());
  assert.deepEqual(clone(Object.fromEntries(actualPairs.map(([sourceId,targetId])=>[`${sourceId}|${targetId}`,byId.get(sourceId).connectionNotes[targetId]]))),expectedCausalNotes);
  for(const [sourceId,targetId] of actualPairs){const sourceRecord=byId.get(sourceId),targetRecord=byId.get(targetId);assert.ok(targetRecord.causeStudyPointIds.includes(sourceId));assert.equal(targetRecord.connectionNotes[sourceId],sourceRecord.connectionNotes[targetId]);assert.match(sourceRecord.connectionNotes[targetId],/\b(?:required|created|let|designed|expanded|increased|sharpened|strengthened|retained|distributed|gave|helped|supplied|led|built|enabled|broadened|rewarded|converted)\b/i);assert.doesNotMatch(sourceRecord.connectionNotes[targetId],/^(?:This|It) happened before|chronolog(?:y|ical order)|\b(?:demonstrated|showed)\b/i);}
});

test('publishes exactly five reciprocal related pairs with identical mechanism-centered comparison notes',()=>{
  const api=evaluate(),byId=new Map(api.records.map(record=>[record.id,record]));
  for(const [left,right,note] of expectedRelatedPairs){const leftRecord=byId.get(left),rightRecord=byId.get(right);assert.ok(leftRecord.relatedStudyPointIds.includes(right));assert.ok(rightRecord.relatedStudyPointIds.includes(left));assert.equal(leftRecord.connectionNotes[right],note);assert.equal(rightRecord.connectionNotes[left],note);}
  assert.equal(api.records.reduce((sum,record)=>sum+record.relatedStudyPointIds.length,0),10);
  const notes=expectedRelatedPairs.map(pair=>pair[2]).join(' ');for(const boundary of ['agriculture','manufacturing','unilaterally','NAFTA','one-party','pluralist','financial institutions','voluntary commitments','targeted disease campaigns','long-term'])assert.match(notes,new RegExp(boundary,'i'));
});

test('rejects location, binding, identity, sequence, count, and date drift',()=>{
  assertInvalid(replace("'11':'Food Security & Unequal Inputs · India / Amritsar–Punjab'","'11':'Wrong place'"),/canonical name/);
  assertInvalid(replace("'11':'world-event-11-3'","'11':'world-event-11-4'"),/main-event binding/);
  assertInvalid(replace("'apwh-u9-amritsar-unequal-access-land-consolidation','11',2","'apwh-u9-amritsar-high-yield-seeds-input-package','11',2"),/duplicate record ID/);
  assertInvalid(replace("P('apwh-u9-amritsar-unequal-access-land-consolidation'","P('apwh-u9-amritsar-high-yield-seeds-input-package'"),/duplicate raw record ID/);
  assertInvalid(replace("'apwh-u9-amritsar-unequal-access-land-consolidation','11',2","'apwh-u9-amritsar-unequal-access-land-consolidation','11',1"),/duplicate sequence|exactly three records/);
  assertInvalid(replace("['apwh-u9-amritsar-food-population-environmental-costs'","['apwh-u9-fourth-record','11',4,'Fourth','1991',1991,1991,'world-event-11-3',['9.9'],['GOV'],['Causation']],\n['apwh-u9-amritsar-food-population-environmental-costs'"),/expected exactly 30 records|exactly three records/);
  assertInvalid(replace("'1978–1984',1978,1984","'1978-1984',1978,1984"),/invalid dateLabel/);
  assertInvalid(replace("'1978–1984',1978,1984","'1978–1985',1978,1984"),/invalid dateLabel/);
});

test('rejects missing, invalid, and duplicate taxonomy values',()=>{
  assertInvalid(replace("['9.1','9.3'],['TEC','ENV']","[],['TEC','ENV']"),/missing topicCodes/);
  assertInvalid(replace("['9.1','9.3'],['TEC','ENV']","['9.1','9.1'],['TEC','ENV']"),/duplicate topicCode/);
  assertInvalid(replace("['9.1','9.3'],['TEC','ENV']","['9.0'],['TEC','ENV']"),/invalid topicCode/);
  assertInvalid(replace("['TEC','ENV'],['Contextualization','Causation']","[],['Contextualization','Causation']"),/missing themeIds/);
  assertInvalid(replace("['TEC','ENV'],['Contextualization','Causation']","['TEC','TEC'],['Contextualization','Causation']"),/duplicate themeId/);
  assertInvalid(replace("['TEC','ENV'],['Contextualization','Causation']","['WAR'],['Contextualization','Causation']"),/invalid themeId/);
  assertInvalid(replace("['TEC','ENV'],['Contextualization','Causation']","['TEC','ENV'],[]"),/missing examSkills/);
  assertInvalid(replace("['TEC','ENV'],['Contextualization','Causation']","['TEC','ENV'],['Causation','Causation']"),/duplicate examSkill/);
  assertInvalid(replace("['TEC','ENV'],['Contextualization','Causation']","['TEC','ENV'],['Recall']"),/invalid examSkill/);
});

test('rejects incomplete, non-English, and malformed learner content',()=>{
  assertInvalid(replace("'High-yield wheat and rice varieties increased harvest potential only when farmers could combine them with irrigation, fertilizer, credit, land, and mechanization.'","''"),/summary/);
  assertInvalid(replace("'Amritsar–Punjab is a representative anchor for Green Revolution change, and seeds alone did not produce equal gains because complementary inputs were distributed unevenly.'","'全球化'"),/significance/);
  assertInvalid(replace("'Indian agricultural officials and Punjab farmers','Distributed new varieties and made choices about irrigation, fertilizer, credit, land, and machinery.'","'','Distributed new varieties and made choices about irrigation, fertilizer, credit, land, and machinery.'"),/keyPeople/);
  assertInvalid(replace("'Green Revolution','The spread of high-yield crop varieties together with the inputs and institutions needed to raise agricultural output.'","'Green Revolution',''"),/keyTerms/);
  assertInvalid(replace("['High-yield wheat varieties spread widely in Punjab during the late 1960s.','Tube wells, fertilizer purchases, rural credit, and tractors helped farmers realize higher yields.']","['Only one statement.']"),/evidence/);
  assertInvalid(replace("'Explain causation by linking new seed varieties to the irrigation, fertilizer, credit, land, and mechanization that made them productive.'","''"),/examConnection/);
  assertInvalid(replace("source:{id:'amsco-apwh-u9',locator}","source:{id:'wrong',locator}"),/source/);
  assertInvalid(replace("source:{id:'amsco-apwh-u9',locator}","source:{id:'amsco-apwh-u9',locator,extra:true}"),/source/);
  assertInvalid(replace('validate();',"Object.defineProperty(RAW_RECORDS[0].evidence,'0',{enumerable:false});validate();"),/evidence/);
});

test('rejects null or hostile raw registries, cards, and graph structures with controlled diagnostics',()=>{
  for(const [search,replacement,rule] of [
    ['const LOCATIONS=Object.freeze({','const LOCATIONS=Object.freeze(null); const UNUSED_LOCATIONS=Object.freeze({',/location registry/],
    ['const BINDINGS=Object.freeze({','const BINDINGS=Object.freeze(null); const UNUSED_BINDINGS=Object.freeze({',/location registry/],
    ['const RAW_RECORDS=[','const RAW_RECORDS=null; const UNUSED_RAW_RECORDS=[',/raw records/],
    ['const CONNECTIONS={','const CONNECTIONS=null; const UNUSED_CONNECTIONS={',/connections must contain exactly/],
    ["const CARD_KEYS=['context','synthesis'];","const CARD_KEYS=null; const UNUSED_CARD_KEYS=['context','synthesis'];",/unit cards/],
    ['const UNIT_CARD_MANIFEST={','const UNIT_CARD_MANIFEST=null; const UNUSED_UNIT_CARD_MANIFEST={',/unit cards/],
  ])assertInvalid(replace(search,replacement),rule);
  assertInvalid(replace("'11':'Food Security & Unequal Inputs · India / Amritsar–Punjab'","get '11'(){throw new Error('accessor leaked');}"),/location registry/);
});

test('rejects unresolved, self, duplicate, and malformed graph links',()=>{
  const [edgeSource,edgeTarget]=localCausalPairs[0],edgeNote=expectedCausalNotes[`${edgeSource}|${edgeTarget}`],edge=`['${edgeSource}','${edgeTarget}','${edgeNote}']`;
  const [relatedSource,relatedTarget,relatedNote]=expectedRelatedPairs[0],relatedEdge=`['${relatedSource}','${relatedTarget}','${relatedNote}']`;
  const unresolved=replace(edge,edge.replace(`'${edgeSource}'`,`'apwh-u9-missing-source'`));
  assert.throws(()=>evaluate(unresolved),error=>{assert.equal(error.name,'Error');assert.match(error.message,/Invalid Unit 9 study record apwh-u9-missing-source: unresolved connection/);return true;});
  assertInvalid(replace(edge,edge.replace(`'${edgeTarget}'`,`'${edgeSource}'`)),/self connection/);
  assertInvalid(replace('causal:[','causal:['+edge+','),/duplicate causal connection/);
  assertInvalid(replace(relatedEdge,relatedEdge.replace(`'${relatedSource}'`,`'apwh-u9-missing-related'`)),/unresolved connection/);
  assertInvalid(replace(relatedEdge,relatedEdge.replace(`'${relatedTarget}'`,`'${relatedSource}'`)),/self connection/);
  assertInvalid(replace('related:[','related:['+relatedEdge+','),/duplicate related connection/);
  const malformed=replace(edge,`['${edgeSource}','${edgeTarget}']`);
  assert.throws(()=>evaluate(malformed),error=>{assert.equal(error.name,'Error');assert.match(error.message,/Invalid Unit 9/);assert.match(error.message,/connection row/);return true;});
  assertInvalid(replace(edge,edge.replace(`'${edgeSource}'`,`Symbol('bad source')`)),/unresolved connection/);
  assertInvalid(replace('related:[','related:['+edge+','),/cross-category connection/);
});

test('publishes exact frozen course-closing cards with no Unit 10 handoff',()=>{
  const api=evaluate();assert.deepEqual(clone(api.unitCards),expectedUnitCards);assert.equal(Object.isFrozen(api.unitCards),true);
  for(const [kind,card] of Object.entries(expectedUnitCards)){assert.equal(api.getUnitCard(kind),api.unitCards[kind]);assert.equal(api.getUnitCard(card.id),api.unitCards[kind]);assert.equal(Object.isFrozen(api.unitCards[kind]),true);assert.equal(Object.isFrozen(api.unitCards[kind].examSkills),true);assert.equal(Object.isFrozen(api.unitCards[kind].takeaways),true);assert.equal(Object.hasOwn(api.unitCards[kind],'skills'),false);}
  assert.doesNotMatch(JSON.stringify(api.unitCards),/Unit 10|u10|handoff/i);
});

test('rejects graph or course-closing card drift before publication',()=>{
  const firstNote=expectedCausalNotes[`${localCausalPairs[0][0]}|${localCausalPairs[0][1]}`];
  assertInvalid(replace(firstNote,'This happened before the next event and shaped its chronology.'),/causal connection does not match|causal mechanism/);
  assertInvalid(replace(firstNote,'This event led to the next event because it happened earlier in chronological order.'),/causal connection does not match|causal mechanism/);
  const relatedNote=expectedRelatedPairs[4][2],vagueRelated='These two developments are both important examples of globalization.',driftedRelated=source.replace(relatedNote,vagueRelated).replace(relatedNote,vagueRelated);assert.notEqual(driftedRelated,source,'related fixture mutation');assertInvalid(driftedRelated,/related comparison does not match/);
  assertInvalid(replace("kind:'context'","kind:'synthesis'"),/card kind/);
  assertInvalid(replace("role:'Unit 9 Context Card'","role:''"),/malformed card/);
  assertInvalid(replace("examSkills:['Contextualization','Causation']","examSkills:['Causation','Causation']"),/card skills/);
  assertInvalid(replace("synthesis:{id:'apwh-u9-synthesis-regional-networks-planetary-interdependence'","synthesis:{id:'apwh-u9-context-post-cold-war-globalized-system'"),/duplicate card ID/);
  assertInvalid(replace("title:'From the End of the Cold War to a Globalized System'","title:'Arbitrary English Title'"),/card contract/);
  assertInvalid(replace('validate();',"Object.defineProperty(UNIT_CARD_MANIFEST.context.takeaways,'0',{enumerable:false});validate();"),/card takeaways/);
});

test('validates the graph twice without mutation and never leaks a TypeError',()=>{
  const api=evaluate(replace('validate();','validate();validate();'));assert.equal(api.records.length,30);
  const graphMalformed=replace('validate();',"validate();CONNECTIONS.causal[0][0]='missing';validate();");assert.throws(()=>evaluate(graphMalformed),error=>{assert.equal(error.name,'Error');assert.match(error.message,/Invalid Unit 9/);assert.match(error.message,/unresolved connection/);return true;});
  const malformed=replace('validate();',"STUDY_MANIFEST[0][0]=Symbol('bad');validate();validate();");assert.throws(()=>evaluate(malformed),error=>{assert.equal(error.name,'Error');assert.match(error.message,/Invalid Unit 9/);assert.match(error.message,/invalid stable ID/);return true;});
});

test('locks the canonical introduction and all five source-ledger columns for exactly thirty records',()=>{
  assert.equal(ledger.startsWith(ledgerIntroduction),true);const rows=parseLedgerRows(ledger);assert.deepEqual(rows,expectedLedgerRows);assert.equal(new Set(rows.map(row=>row[0])).size,30);
  for(let index=0;index<rows.length;index+=1){const manifest=expectedManifest[index];assert.equal(rows[index][0],manifest[0]);assert.equal(rows[index][1],manifest[8].join(', '));assert.equal(rows[index][2],manifest[7]);assert.equal(rows[index][3],L(manifest[8]));assert.ok(expectedLocations.has(manifest[1]));}
});

test('tokenizes escaped Markdown pipes without creating extra ledger columns',()=>{
  assert.deepEqual(parseMarkdownRowCells('| one | two \\| literal pipe | three | four | five |'),['one','two | literal pipe','three','four','five']);
  assert.deepEqual(parseMarkdownRowCells(String.raw`| one | three \\\| literal pipe | three | four | five |`),['one',String.raw`three \| literal pipe`,'three','four','five']);
});

test('keeps anchor, institution, and five cross-case analytical caveats in the Unit 9 ledger',()=>{
  const claimsById=new Map(parseLedgerRows(ledger).map(cells=>[cells[0],cells[4]]));
  for(const [id,boundary] of [
    ['apwh-u9-amritsar-high-yield-seeds-input-package',/representative regional anchor/],
    ['apwh-u9-san-francisco-computing-internet-information-costs',/one commercialization anchor/],
    ['apwh-u9-washington-bretton-woods-financial-institutions',/World Bank, IMF, and WTO remain distinct institutions/],
    ['apwh-u9-paris-voluntary-climate-governance-limits',/UN climate process/],
    ['apwh-u9-geneva-polio-ebola-coordination-limits',/coordination anchor/],
    ['apwh-u9-seoul-digital-platforms-transnational-audiences',/Seoul is an anchor/],
    ['apwh-u9-amritsar-unequal-access-land-consolidation',/agriculture from export manufacturing/],
    ['apwh-u9-ciudad-juarez-nafta-maquiladora-expansion',/unilateral Chinese reform/],
    ['apwh-u9-beijing-tiananmen-protest-repression',/pluralist summit protest/],
    ['apwh-u9-washington-institutional-power-benefits-criticism',/financial conditionality from voluntary rights-and-climate commitments/],
    ['apwh-u9-geneva-polio-ebola-coordination-limits',/targeted disease campaigns from long climate mitigation/],
  ])assert.match(claimsById.get(id),boundary);
});

test('rejects ledger missing or extra rows, ordering, columns, trailing content, vague citations, page numbers, and missing caveats',()=>{
  const firstRow=ledger.split('\n').find(line=>line.includes('apwh-u9-amritsar-high-yield-seeds-input-package')),secondRow=ledger.split('\n').find(line=>line.includes('apwh-u9-amritsar-unequal-access-land-consolidation')),lastRow=ledger.split('\n').find(line=>line.includes('apwh-u9-seoul-hybrid-culture-exports-soft-power')),fourColumnRow=`${firstRow.split('|').slice(0,-2).join('|')}|`;
  const cases=[
    [ledger.replace(`${ledgerIntroduction}\n\n${ledgerHeader}`,`${ledgerIntroduction}\n\nInserted prose.\n\n${ledgerHeader}`),/table header must immediately follow canonical introduction/],
    [ledger.replace(firstRow,`${firstRow} trailing garbage`),/row must start and end with pipe delimiters/],
    [ledger.replace(firstRow,fourColumnRow),/row must contain exactly five columns/],
    [ledger.replace(firstRow,firstRow.replace(/ \|$/,' | extra |')),/row must contain exactly five columns/],
    [ledger.replace(lastRow,''),/expected exactly 30 data rows/],
    [ledger.replace(firstRow,`${firstRow}\n${firstRow}`),/expected exactly 30 data rows/],
    [ledger.replace(`${firstRow}\n${secondRow}`,`${secondRow}\n${firstRow}`),/row 1 does not match the canonical record order and fields/],
    [ledger.replace('AMSCO AP World History, Unit 9, Topics 9.1 and 9.3','AMSCO AP World History, Unit 9'),/vague source locator/],
    [ledger.replace('AMSCO AP World History, Unit 9, Topics 9.1 and 9.3','AMSCO AP World History, Unit 9, Topics 9.1 and 9.3, p. 742'),/unverified page number/],
    [ledger.replace('the local causal link is project-authored analysis','the local link follows the sources'),/missing source-analysis distinction/],
    [ledger.replace('world-event-11-3','world-event-11-4'),/row 1 does not match the canonical record order and fields/],
    [`${ledger}\nTrailing garbage`,/unexpected trailing content/],
  ];
  for(const [candidate,message] of cases){assert.notEqual(candidate,ledger,'ledger fixture mutation');assert.throws(()=>parseLedgerRows(candidate),message);}
});
