import assert from 'node:assert/strict';
import test from 'node:test';
import { existsSync, readFileSync } from 'node:fs';
import vm from 'node:vm';

const moduleUrl=new URL('../data/apwh-u9-location-study.js',import.meta.url);
const source=existsSync(moduleUrl)?readFileSync(moduleUrl,'utf8'):'';
const evaluateSandbox=(code=source,seed={})=>{const sandbox={...seed};sandbox.window=sandbox;vm.runInNewContext(code,sandbox);return sandbox;};
const evaluate=(code=source,seed={})=>evaluateSandbox(code,seed).APWH_U9_LOCATION_STUDY;
const expectedLocations=new Map([
  ['11','Food Security & Unequal Inputs · India / Amritsar–Punjab'],
  ['70','Digital Infrastructure & Knowledge Economy · United States / San Francisco'],
  ['15','Special Economic Zones & Export Manufacturing · China / Guangzhou'],
  ['65','Free Trade & Maquiladoras · Mexico / Ciudad Juárez'],
  ['5','Market Reform & Political Control · China / Beijing'],
  ['54','Global Financial Governance · United States / Washington, D.C.'],
  ['112','Resistance to Globalization · United States / Seattle'],
  ['24','Human Rights & Climate Governance · France / Paris'],
  ['34','Global Health Cooperation · Switzerland / Geneva'],
  ['110','Digital Culture & Soft Power · South Korea / Seoul'],
]);
const expectedBindings=new Map([
  ['11','world-event-11-3'],['70','world-event-70-2'],['15','world-event-15-1'],['65','world-event-65-0'],['5','world-event-5-13'],['54','world-event-54-5'],['112','world-event-112-0'],['24','world-event-24-9'],['34','world-event-34-2'],['110','world-event-110-1'],
]);
const expectedManifest=[
  ['apwh-u9-amritsar-high-yield-seeds-input-package','11',1,'High-Yield Seeds and Complementary Inputs','1960s–1970s',1960,1979,'world-event-11-3',['9.1','9.3'],['TEC','ENV'],['Contextualization','Causation']],
  ['apwh-u9-amritsar-unequal-access-land-consolidation','11',2,'Unequal Access, Mechanization, and Land Consolidation','1960s–1980s',1960,1989,'world-event-11-3',['9.3','9.4'],['ECN','SIO'],['Causation','Comparison']],
  ['apwh-u9-amritsar-food-population-environmental-costs','11',3,'Food Supply, Population Growth, and Environmental Costs','1970s–2010s',1970,2019,'world-event-11-3',['9.3','9.9'],['ENV','SIO'],['Causation','CCOT']],
  ['apwh-u9-san-francisco-public-research-digital-infrastructure','70',1,'Public Research and Digital Infrastructure','1940s–1980s',1940,1989,'world-event-70-2',['9.1'],['TEC','GOV'],['Contextualization']],
  ['apwh-u9-san-francisco-computing-internet-information-costs','70',2,'Computing, Internet, and Lower Information Costs','1970s–1990s',1970,1999,'world-event-70-2',['9.1','9.4'],['TEC','ECN'],['Causation']],
  ['apwh-u9-san-francisco-knowledge-economy-distributed-production','70',3,'Knowledge Economy and Uneven Global Production','1990s–2010s',1990,2019,'world-event-70-2',['9.4','9.9'],['ECN','SIO'],['Causation','CCOT']],
  ['apwh-u9-guangzhou-market-reform-special-economic-zones','15',1,'Market Reform and Special Economic Zones','1978–1984',1978,1984,'world-event-15-1',['9.4'],['ECN','GOV'],['Contextualization','Causation']],
  ['apwh-u9-guangzhou-foreign-investment-export-manufacturing','15',2,'Foreign Investment and Export Manufacturing','1980s–2001',1980,2001,'world-event-15-1',['9.4'],['ECN','GOV'],['Causation']],
  ['apwh-u9-guangzhou-supply-chain-labor-environmental-costs','15',3,'Supply-Chain Expansion, Labor, and Environmental Costs','2001–2010s',2001,2019,'world-event-15-1',['9.3','9.4','9.9'],['ECN','SIO','ENV'],['Causation','CCOT']],
  ['apwh-u9-ciudad-juarez-border-industrialization','65',1,'Border Industrialization before NAFTA','1965–1993',1965,1993,'world-event-65-0',['9.4'],['ECN','GOV'],['Contextualization']],
  ['apwh-u9-ciudad-juarez-nafta-maquiladora-expansion','65',2,'NAFTA and Maquiladora Expansion','1994–2000s',1994,2009,'world-event-65-0',['9.4'],['ECN','GOV'],['Causation']],
  ['apwh-u9-ciudad-juarez-employment-gender-labor-environment','65',3,'Employment, Gender, Labor, and Environmental Tradeoffs','1990s–2010s',1990,2019,'world-event-65-0',['9.3','9.4','9.9'],['ECN','SIO','ENV'],['Comparison','CCOT']],
  ['apwh-u9-beijing-market-reform-political-control','5',1,'Market Reform without Political Liberalization','1978–1989',1978,1989,'world-event-5-13',['9.4','9.5'],['ECN','GOV'],['Contextualization','Causation']],
  ['apwh-u9-beijing-tiananmen-protest-repression','5',2,'Tiananmen Protest and State Repression','1989',1989,1989,'world-event-5-13',['9.5'],['GOV','SIO'],['Causation']],
  ['apwh-u9-beijing-wto-integration-information-control','5',3,'WTO Integration and Controlled Information','2001–2010s',2001,2019,'world-event-5-13',['9.4','9.5','9.9'],['GOV','ECN','TEC'],['Causation','CCOT']],
  ['apwh-u9-washington-bretton-woods-financial-institutions','54',1,'Bretton Woods and Postwar Financial Institutions','1944–1945',1944,1945,'world-event-54-5',['9.8'],['GOV','ECN'],['Contextualization']],
  ['apwh-u9-washington-development-lending-conditionality','54',2,'Development Lending and Policy Conditionality','1950s–2000s',1950,2009,'world-event-54-5',['9.4','9.8'],['ECN','GOV'],['Causation']],
  ['apwh-u9-washington-institutional-power-benefits-criticism','54',3,'Institutional Power, Development Claims, and Criticism','1990s–2010s',1990,2019,'world-event-54-5',['9.7','9.8','9.9'],['GOV','ECN'],['Causation','Comparison']],
  ['apwh-u9-seattle-wto-expansion-rulemaking-criticism','112',1,'WTO Expansion and Rule-Making Criticism','1995–1999',1995,1999,'world-event-112-0',['9.7','9.8'],['GOV','ECN'],['Contextualization','Causation']],
  ['apwh-u9-seattle-coalition-protest-digital-organization','112',2,'Coalition Protest and Digital Organization','1999',1999,1999,'world-event-112-0',['9.1','9.5','9.7'],['GOV','SIO','TEC'],['Causation']],
  ['apwh-u9-seattle-fair-trade-labor-continuing-resistance','112',3,'Fair Trade, Labor Standards, and Continuing Resistance','2000s–2010s',2000,2019,'world-event-112-0',['9.5','9.7','9.9'],['GOV','ECN','SIO'],['CCOT','Comparison']],
  ['apwh-u9-paris-universal-rights-global-norm','24',1,'Universal Rights as a Global Norm','1948',1948,1948,'world-event-24-9',['9.5','9.8'],['GOV','CDI'],['Contextualization']],
  ['apwh-u9-paris-kyoto-burden-sharing-debate','24',2,'Kyoto-to-Paris Burden-Sharing Debate','1997–2015',1997,2015,'world-event-24-9',['9.3','9.8'],['ENV','GOV'],['Causation','Comparison']],
  ['apwh-u9-paris-voluntary-climate-governance-limits','24',3,'Paris Agreement and the Limits of Voluntary Governance','2015–2019',2015,2019,'world-event-24-9',['9.3','9.8','9.9'],['ENV','GOV'],['Causation','CCOT']],
  ['apwh-u9-geneva-vaccination-smallpox-eradication','34',1,'Vaccination Networks and Smallpox Eradication','1967–1980',1967,1980,'world-event-34-2',['9.2','9.8'],['TEC','GOV'],['Contextualization','Causation']],
  ['apwh-u9-geneva-hiv-treatment-unequal-access','34',2,'HIV/AIDS Treatment and Unequal Access','1980s–2000s',1980,2009,'world-event-34-2',['9.2','9.9'],['TEC','SIO'],['Causation','Comparison']],
  ['apwh-u9-geneva-polio-ebola-coordination-limits','34',3,'Polio, Ebola, and the Limits of Health Coordination','1988–2010s',1988,2019,'world-event-34-2',['9.2','9.8','9.9'],['TEC','GOV'],['Causation','CCOT']],
  ['apwh-u9-seoul-state-supported-cultural-industries','110',1,'State Support for Cultural Industries','1990s–2000s',1990,2009,'world-event-110-1',['9.4','9.6'],['CDI','ECN','GOV'],['Contextualization','Causation']],
  ['apwh-u9-seoul-digital-platforms-transnational-audiences','110',2,'Digital Platforms and Transnational Audiences','2000s–2010s',2000,2019,'world-event-110-1',['9.1','9.6'],['CDI','TEC','ECN'],['Causation']],
  ['apwh-u9-seoul-hybrid-culture-exports-soft-power','110',3,'Hybrid Culture, Exports, and Soft Power','2000s–2010s',2000,2019,'world-event-110-1',['9.6','9.9'],['CDI','ECN'],['Comparison','CCOT']],
];
const L=topics=>`AMSCO AP World History, Unit 9, ${topics.length===1?'Topic':'Topics'} ${topics.length===1?topics[0]:topics.length===2?topics.join(' and '):`${topics.slice(0,-1).join(', ')}, and ${topics.at(-1)}`}`;
const P=(id,summary,significance,person,role,term,explanation,evidence,examConnection,locator)=>({id,summary,significance,keyPeople:[{name:person,role}],keyTerms:[{term,explanation}],evidence,examConnection,source:{id:'amsco-apwh-u9',locator}});
const expectedContent=[
P('apwh-u9-amritsar-high-yield-seeds-input-package','High-yield wheat and rice varieties increased harvest potential only when farmers could combine them with irrigation, fertilizer, credit, land, and mechanization.','Amritsar–Punjab is a representative anchor for Green Revolution change, and seeds alone did not produce equal gains because complementary inputs were distributed unevenly.','Indian agricultural officials and Punjab farmers','Distributed new varieties and made choices about irrigation, fertilizer, credit, land, and machinery.','Green Revolution','The spread of high-yield crop varieties together with the inputs and institutions needed to raise agricultural output.',['High-yield wheat varieties spread widely in Punjab during the late 1960s.','Tube wells, fertilizer purchases, rural credit, and tractors helped farmers realize higher yields.'],'Explain causation by linking new seed varieties to the irrigation, fertilizer, credit, land, and mechanization that made them productive.',L(['9.1','9.3'])),
P('apwh-u9-amritsar-unequal-access-land-consolidation','Farmers with larger holdings and better access to water, loans, fertilizer, and machinery often adopted the new package faster than smallholders.','Unequal input access could widen rural inequality, encourage land consolidation, and reduce demand for some forms of agricultural labor.','Punjab landowners, smallholders, and agricultural laborers','Experienced different costs and benefits from capital-intensive agricultural change.','land consolidation','The concentration of farmland into fewer or larger holdings through purchase, debt, or displacement.',['Larger landowners were generally better positioned to obtain formal credit and purchase machinery.','Mechanized pumping and harvesting raised capital costs and changed demand for hired labor.'],'Compare how land, credit, irrigation, and machinery shaped unequal gains for large landowners, smallholders, and laborers.',L(['9.3','9.4'])),
P('apwh-u9-amritsar-food-population-environmental-costs','Higher grain output supported food security and population growth, while intensive irrigation and chemical inputs created long-term water and soil pressures.','The case joins a major increase in food supply to uneven social gains and environmental costs rather than treating agricultural technology as an unqualified success.','Punjab farming communities and environmental officials','Managed expanding food production alongside falling water tables and soil stress.','groundwater depletion','The decline of underground water reserves when pumping exceeds natural recharge.',['India moved from chronic grain shortages toward much greater wheat and rice output after the Green Revolution.','Intensive groundwater pumping and fertilizer use contributed to falling water tables and soil degradation in Punjab.'],'Trace continuity and change by weighing increased food supply and population support against water, soil, and inequality costs.',L(['9.3','9.9'])),
P('apwh-u9-san-francisco-public-research-digital-infrastructure','Public universities, defense research, and government procurement supported semiconductor and computing networks that private firms later commercialized.','San Francisco is a representative anchor for a wider Bay Area ecosystem in which public investment helped create digital infrastructure and skilled labor.','Public research agencies, universities, and technology firms','Funded research, trained workers, and commercialized semiconductor and computing applications.','semiconductor','A material and electronic component used to control electrical signals in modern computing devices.',['Federal defense and research spending supported electronics laboratories and university work in California.','Integrated-circuit firms and a skilled workforce clustered around the wider San Francisco Bay Area.'],'Contextualize private innovation by identifying the public research, procurement, education, and infrastructure that supported it.',L(['9.1'])),
P('apwh-u9-san-francisco-computing-internet-information-costs','Advances in semiconductors, personal computing, and internet networks sharply lowered information costs for storing, processing, and transmitting data.','Cheaper communication accelerated market integration across distance, while the Bay Area was one commercialization hub among many contributors to global networks.','Computer engineers, public network researchers, and entrepreneurs','Improved computing capacity and expanded interoperable digital networks.','internet','A global network of interconnected computer networks that exchange data through common protocols.',['Microprocessor costs fell while computing power increased during the late twentieth century.','Publicly funded networking research and commercial services connected users across institutions and countries.'],'Explain how computing and internet infrastructure reduced information costs without assigning a global network to one city.',L(['9.1','9.4'])),
P('apwh-u9-san-francisco-knowledge-economy-distributed-production','Digital firms concentrated design, software, finance, and knowledge work while distributed production placed manufacturing and support functions in global supply chains.','The knowledge economy created high-value work and rapid coordination but also widened regional and occupational inequality.','Technology firms and global supply-chain workers','Coordinated knowledge-intensive services with production performed across multiple countries.','knowledge economy','An economy in which information, expertise, research, and intellectual property are major sources of value.',['Bay Area firms retained design and software functions while contracting hardware production to factories abroad.','Digital platforms allowed teams and suppliers to coordinate production across long distances.'],'Trace how lower information costs changed the location of knowledge work and distributed production while preserving uneven gains.',L(['9.4','9.9'])),
P('apwh-u9-guangzhou-market-reform-special-economic-zones','Deng-era leaders authorized market reforms and special economic zones in coastal Guangdong to test investment, trade, and production incentives.','Export growth followed a state choice about law, infrastructure, and location rather than an automatic technology effect.','Deng Xiaoping and Chinese state officials','Authorized reform experiments and coastal zones while retaining Communist Party political control.','special economic zone','A designated area where a government applies distinct trade, investment, tax, or regulatory policies.',['China began major market-oriented reforms after 1978 under Deng Xiaoping.','Shenzhen and other Guangdong zones received preferential policies and infrastructure near export routes.'],'Explain why special economic zone growth depended on state choices, geography, and investment rules rather than technology alone.',L(['9.4'])),
P('apwh-u9-guangzhou-foreign-investment-export-manufacturing','Special policies attracted foreign direct investment and linked Guangdong factories to export markets and transnational production networks.','Foreign capital, abundant labor, state infrastructure, and port access combined to expand export manufacturing.','Chinese local governments and foreign investors','Built factories, infrastructure, and supplier networks for export-oriented production.','foreign direct investment','Investment by an entity based in one country that establishes or controls productive assets in another.',['Overseas Chinese and multinational investors financed factories across the Pearl River Delta.','Manufactured exports expanded through ports serving Guangzhou, Shenzhen, and Hong Kong.'],'Build a multicausal argument connecting foreign investment, labor, infrastructure, policy incentives, and export access.',L(['9.4'])),
P('apwh-u9-guangzhou-supply-chain-labor-environmental-costs','After China joined the WTO, firms expanded supply-chain production in the Pearl River Delta and drew migrant labor into export factories.','Supply relocation increased jobs and output while producing demanding labor regimes, pollution, and uneven regional gains.','Migrant workers, factory managers, and environmental regulators','Produced export goods and contested working conditions and environmental damage.','supply-chain relocation','The movement of production stages to new regions to lower costs or reach suppliers and markets.',['China entered the World Trade Organization in 2001 and manufactured exports rose rapidly.','Pearl River Delta factories relied on migrant labor and generated significant air and water pollution.'],'Trace continuity and change after WTO entry by weighing supply-chain growth against labor and environmental costs.',L(['9.3','9.4','9.9'])),
P('apwh-u9-ciudad-juarez-border-industrialization','Mexico created the Border Industrialization Program before NAFTA to encourage foreign-owned assembly plants along the United States border.','The 1965 program established the maquiladora model, so border industrialization cannot be attributed to NAFTA alone.','Mexican officials and border manufacturers','Created tariff and investment arrangements for export assembly along the northern border.','Border Industrialization Program','Mexico’s program promoting export-oriented assembly plants in its northern border region.',['Mexico launched the Border Industrialization Program in 1965.','Ciudad Juárez plants imported components, assembled goods, and re-exported finished products.'],'Contextualize NAFTA by distinguishing the earlier Border Industrialization Program from later free-trade expansion.',L(['9.4'])),
P('apwh-u9-ciudad-juarez-nafta-maquiladora-expansion','NAFTA reduced trade barriers and encouraged cross-border production networks, accelerating maquiladora expansion around Ciudad Juárez.','The agreement enlarged an existing assembly system by making components, capital, and finished goods easier to move across North America.','Mexican, United States, and Canadian trade officials','Negotiated rules that increased regional trade and investment integration.','NAFTA','The 1994 agreement reducing many trade and investment barriers among Mexico, the United States, and Canada.',['NAFTA took effect in 1994 among Mexico, the United States, and Canada.','Maquiladora employment and export production expanded along the northern Mexican border during the 1990s.'],'Explain how NAFTA accelerated rather than originated maquiladora development.',L(['9.4'])),
P('apwh-u9-ciudad-juarez-employment-gender-labor-environment','Maquiladora employment expanded, especially for women and migrants, while workers faced low pay, insecurity, gendered risks, and industrial pollution.','Export manufacturing shows that job creation could coexist with labor vulnerability, gender inequality, and environmental damage.','Maquiladora workers and labor organizers','Produced export goods and organized around wages, safety, gender violence, and workplace rights.','maquiladora','An export-oriented factory in Mexico that imports components for assembly and re-exports finished goods.',['Women made up a large share of early maquiladora workforces in Ciudad Juárez.','Rapid industrial growth strained water, waste, housing, and pollution controls along the border.'],'Compare employment gains with gender, labor, and pollution tradeoffs in maquiladora production.',L(['9.3','9.4','9.9'])),
P('apwh-u9-beijing-market-reform-political-control','Chinese leaders expanded market incentives and foreign trade after 1978 while preserving one-party political authority.','Market reform did not automatically bring political liberalization, demonstrating that economic change and political control could develop together.','Deng Xiaoping and the Chinese Communist Party','Directed market-oriented reforms while maintaining one-party rule.','reform and opening','China’s post-1978 program of market incentives, foreign investment, and wider engagement with world trade.',['Household responsibility reforms and township enterprises expanded market activity after 1978.','The Chinese Communist Party retained control of national political institutions throughout the reform era.'],'Contextualize Chinese globalization by separating market reform from political liberalization.',L(['9.4','9.5'])),
P('apwh-u9-beijing-tiananmen-protest-repression','Students and other citizens demanded political change in 1989, and the state used military force to end the Tiananmen Square demonstrations.','The repression showed that leaders chose coercive political control even as economic reform continued.','Student demonstrators and Chinese state leaders','Organized demands for reform and ordered or carried out the suppression of protests.','Tiananmen Square protests','The 1989 Beijing demonstrations for political reform that ended in a violent military crackdown.',['Large demonstrations occupied Tiananmen Square during the spring of 1989.','Chinese troops and armored vehicles cleared central Beijing on 3–4 June 1989.'],'Explain how state repression preserved political control without treating the outcome as an automatic result of market reform.',L(['9.5'])),
P('apwh-u9-beijing-wto-integration-information-control','WTO membership deepened China’s trade integration while the state expanded censorship, surveillance, and platform controls over digital information.','Economic integration did not cause democratization; leaders combined world-market participation with information control.','Chinese trade officials and internet regulators','Managed WTO integration while restricting political information and digital communication.','Great Firewall','The laws, filtering systems, and platform controls used by the Chinese state to regulate internet access and content.',['China joined the World Trade Organization in 2001.','Authorities blocked websites, filtered searches, and required domestic platforms to police online content.'],'Trace deeper WTO integration alongside continued one-party rule and evolving information control.',L(['9.4','9.5','9.9'])),
P('apwh-u9-washington-bretton-woods-financial-institutions','The Bretton Woods conference designed the IMF and World Bank framework for postwar monetary stability and reconstruction; the WTO emerged later from a separate trade system.','Washington, D.C. is a headquarters anchor, and the World Bank, IMF, and WTO were distinct institutions with different origins and functions.','Bretton Woods delegates and postwar governments','Created multilateral monetary and development institutions after World War II.','Bretton Woods institutions','The International Monetary Fund and World Bank organizations established from the 1944 Bretton Woods agreements.',['Delegates from forty-four Allied countries met at Bretton Woods in 1944.','The IMF addressed monetary stability, while the World Bank initially financed reconstruction and development.'],'Contextualize financial governance by distinguishing the IMF and World Bank from the later WTO trade regime.',L(['9.8'])),
P('apwh-u9-washington-development-lending-conditionality','The World Bank financed development projects, while the IMF offered balance-of-payments support that often required borrowers to adopt policy conditions.','Lending could fund infrastructure or stabilize currencies, but conditionality could also reduce policy autonomy and impose social costs.','World Bank and IMF officials with borrowing governments','Negotiated development lending, stabilization programs, and attached policy conditions.','conditionality','Economic or administrative policy changes that a lending institution requires a borrower to adopt.',['World Bank loans financed dams, roads, schools, and other development projects.','IMF programs often required fiscal restraint, currency changes, or market-oriented reforms.'],'Explain how lending and conditionality produced both claimed development gains and contested social costs.',L(['9.4','9.8'])),
P('apwh-u9-washington-institutional-power-benefits-criticism','Supporters credited global institutions with development finance and trade rules, while critics challenged unequal voting power and policy influence.','Institutional outcomes reflected cooperation and power imbalances because wealthy states held disproportionate votes and bargaining leverage.','Member governments, institutional officials, and civil-society critics','Debated development benefits, governance rules, voting power, and criticism of accountability.','weighted voting','A system in which members have different vote shares, often connected to financial contributions.',['United States voting power has been especially large in the IMF and World Bank.','Critics linked some adjustment programs to public-spending cuts and protested global economic rules.'],'Compare claimed gains in finance and rule making with criticism of voting power, conditionality, and unequal influence.',L(['9.7','9.8','9.9'])),
P('apwh-u9-seattle-wto-expansion-rulemaking-criticism','The WTO expanded a rules-based trade system, and its 1999 Seattle ministerial focused criticism on transparency, labor, and environmental consequences.','Resistance targeted how global trade rules were made and whose interests they served, not simply international exchange.','WTO delegates and globalization critics','Debated trade negotiations, institutional authority, and public accountability.','WTO ministerial conference','A meeting of World Trade Organization members that makes major decisions about negotiations and trade rules.',['The WTO began operating in 1995 as the successor to the GATT trade framework.','Its Seattle ministerial opened in November 1999 amid disputes and mass protest.'],'Contextualize Seattle by connecting WTO expansion to criticism of rule making, labor, and the environment.',L(['9.7','9.8'])),
P('apwh-u9-seattle-coalition-protest-digital-organization','Labor unions, environmentalists, students, and human-rights advocates built a coalition and used internet communication to organize protest.','Internet networks lowered organizing costs, while coalition building and on-the-ground action made Seattle mobilization possible.','Labor, environmental, student, and human-rights organizers','Coordinated demonstrations and public arguments across distinct movements.','digital mobilization','The use of networked communication to coordinate collective action, share information, and recruit participants.',['Organizers used email lists and websites to circulate plans before the 1999 ministerial.','Tens of thousands of protesters disrupted access to meeting sites in central Seattle.'],'Explain how internet organizing and a labor-environment coalition contributed to protest without reducing mobilization to technology.',L(['9.1','9.5','9.7'])),
P('apwh-u9-seattle-fair-trade-labor-continuing-resistance','After Seattle, activists promoted fair trade, labor standards, environmental safeguards, and continued resistance at later global summits.','The movement continued criticism of unequal globalization while shifting among protest, consumer campaigns, advocacy, and reform.','Fair-trade advocates and transnational labor networks','Pressed for labor protections, environmental standards, and accountable trade rules.','fair trade','An approach to exchange seeking better prices, labor conditions, environmental practices, and producer bargaining power.',['Fair-trade certification linked consumer purchases to standards for producers and workers.','Global justice activists continued resistance at later WTO, IMF, World Bank, and Group of Eight meetings.'],'Trace continuity and change from the Seattle coalition to later fair trade, labor, and global-justice campaigns.',L(['9.5','9.7','9.9'])),
P('apwh-u9-paris-universal-rights-global-norm','The UN adopted the Universal Declaration of Human Rights in Paris, articulating rights as a global standard without automatic enforcement.','Paris is a representative diplomacy anchor for a broader human rights framework negotiated by delegates from many societies.','Eleanor Roosevelt and United Nations delegates','Drafted and negotiated universal civil, political, social, and economic rights.','Universal Declaration of Human Rights','The 1948 United Nations declaration setting a common global standard for human rights.',['The UN General Assembly adopted the declaration in Paris on 10 December 1948.','The declaration included civil and political rights as well as social and economic rights.'],'Contextualize human rights governance by distinguishing a global norm from a binding enforcement mechanism.',L(['9.5','9.8'])),
P('apwh-u9-paris-kyoto-burden-sharing-debate','Climate negotiations from Kyoto to Paris struggled over how industrialized and developing states should divide responsibility for emissions reductions.','Burden sharing remained contested because historical emissions, current emissions, development needs, and sovereignty supported different claims.','Climate negotiators from industrialized and developing states','Debated differentiated responsibility, targets, finance, and national sovereignty.','common but differentiated responsibilities','The principle that all states share environmental duties but have different obligations because of capacity and historical contribution.',['The 1997 Kyoto Protocol assigned binding targets mainly to industrialized countries.','Negotiations toward Paris sought wider participation through nationally designed commitments.'],'Compare Kyoto and Paris approaches to burden sharing, sovereignty, participation, and enforcement.',L(['9.3','9.8'])),
P('apwh-u9-paris-voluntary-climate-governance-limits','The Paris Agreement used nationally determined contributions, reporting, and review to coordinate climate action while leaving target levels nationally chosen.','Broad participation increased, but voluntary commitments and weak enforcement limited guaranteed emissions reductions.','National climate negotiators and UN climate officials','Submitted, reviewed, and revised national climate commitments under a common framework.','nationally determined contribution','A climate-action target and plan that each party defines for itself under the Paris Agreement.',['Nearly every state adopted the Paris Agreement in 2015.','The agreement required reporting and renewed pledges but no single enforceable target for every country.'],'Evaluate broad participation and transparency against sovereignty and enforcement limits in the Paris Agreement.',L(['9.3','9.8','9.9'])),
P('apwh-u9-geneva-vaccination-smallpox-eradication','The WHO coordinated surveillance, vaccination, and assistance that helped eradicate smallpox worldwide.','Geneva is a coordination anchor for a campaign whose success depended on national health workers, local participation, and targeted vaccination.','WHO officials and national vaccination teams','Coordinated surveillance, vaccine delivery, case tracing, and containment across borders.','ring vaccination','The strategy of vaccinating contacts around detected cases to interrupt disease transmission.',['The WHO intensified the global smallpox eradication campaign in 1967.','The World Health Assembly declared smallpox eradicated in 1980.'],'Explain how WHO coordination, vaccination, surveillance, and local implementation combined to eradicate smallpox.',L(['9.2','9.8'])),
P('apwh-u9-geneva-hiv-treatment-unequal-access','Researchers and health agencies expanded antiretroviral treatment for HIV, but patents, prices, infrastructure, and stigma produced unequal access.','Medical innovation did not distribute itself evenly; resources, state capacity, activism, and policy choices shaped treatment access.','People living with HIV, treatment activists, and health agencies','Demanded affordable medicines and organized prevention and treatment programs.','antiretroviral therapy','Drug combinations that suppress HIV replication and allow many patients to live longer lives.',['Combination antiretroviral therapy became effective in the mid-1990s.','Generic drugs and international financing later expanded HIV treatment in many lower-income countries.'],'Compare effective HIV treatment with unequal access caused by price, patents, infrastructure, stigma, and resources.',L(['9.2','9.9'])),
P('apwh-u9-geneva-polio-ebola-coordination-limits','WHO-led programs coordinated polio vaccination and Ebola response, but weak surveillance, distrust, conflict, state capacity, and resources constrained implementation.','Global cooperation could mobilize expertise without eliminating the need for capable states and trusted local health systems.','WHO responders, health ministries, and community workers','Coordinated surveillance, vaccination, treatment, and public communication during disease campaigns.','disease surveillance','The systematic collection and analysis of health data used to detect cases and guide action.',['The Global Polio Eradication Initiative began in 1988 and reduced cases dramatically.','The 2014–2016 West African Ebola epidemic exposed shortages in surveillance, clinics, staff, and resources.'],'Trace why polio and Ebola coordination remained limited by surveillance, state capacity, trust, conflict, and resources.',L(['9.2','9.8','9.9'])),
P('apwh-u9-seoul-state-supported-cultural-industries','South Korean governments treated film, television, music, and digital media as strategic cultural industries and supported training, infrastructure, and exports.','Seoul is a representative anchor for a national strategy in which state support and private creativity interacted.','South Korean cultural agencies and media firms','Invested in production capacity, creative training, and export promotion.','Hallyu','The transnational popularity of South Korean popular culture, often called the Korean Wave.',['South Korea expanded cultural-industry policy and media investment after the 1990s.','Television dramas, film, and popular music became important cultural exports.'],'Contextualize cultural industries by linking state support, private firms, creative labor, and changing markets.',L(['9.4','9.6'])),
P('apwh-u9-seoul-digital-platforms-transnational-audiences','Broadband networks, streaming sites, social media, and fan communities allowed Korean music and drama to reach transnational audiences rapidly.','Digital distribution lowered barriers, while translation, recommendation systems, and organized fans actively built audiences.','Korean media producers and transnational fan communities','Distributed, translated, promoted, and discussed cultural products through digital platforms.','digital distribution','The circulation of media through networked platforms rather than only physical copies or broadcast channels.',['South Korea developed high levels of broadband access and digital-media use.','Online video, streaming, and social platforms carried Korean music and drama across continents.'],'Explain how digital platforms and fan networks changed the scale and speed of transnational audiences.',L(['9.1','9.6'])),
P('apwh-u9-seoul-hybrid-culture-exports-soft-power','Korean producers combined local language and themes with global genres, production styles, and marketing to create hybrid culture exports.','Seoul is a representative anchor for soft power, and globalization was not synonymous with Americanization.','Korean artists, producers, and cultural diplomats','Created hybrid media exports that influenced foreign audiences and national image.','soft power','The ability to attract and influence others through culture, values, and reputation rather than coercion.',['K-pop blended Korean lyrics and performance systems with hip-hop, electronic, and other transnational styles.','The South Korean state used cultural exports in tourism and public-diplomacy campaigns.'],'Compare cultural borrowing and local adaptation to show how hybrid exports generated economic value and soft power.',L(['9.6','9.9'])),
];
const placeholderEdge=['apwh-u9-amritsar-high-yield-seeds-input-package','apwh-u9-amritsar-unequal-access-land-consolidation','High-yield seeds raised output only when combined with costly inputs, so unequal access shaped who received the largest gains.'];
const expectedUnitCards={
  context:{id:'apwh-u9-context-accelerating-global-connections',kind:'context',role:'Unit 9 Context Card',title:'Accelerating Global Connections',examSkills:['Contextualization','Causation'],summary:'New technologies, state policies, and international institutions accelerated the movement of goods, capital, information, culture, and disease after 1900. These connections built on earlier networks while changing their speed, scale, and reach.',prompt:'Which technologies and political choices accelerated global connections after 1900?',takeaways:['Communication and transportation reduced the cost of coordinating across distance.','Governments and institutions shaped the rules under which integration occurred.','Faster connections distributed opportunities and risks unevenly.']},
  synthesis:{id:'apwh-u9-synthesis-globalization-benefits-resistance',kind:'synthesis',role:'Unit 9 Synthesis Card',title:'Globalization, Uneven Benefits, and Resistance',examSkills:['Comparison','CCOT'],summary:'Global integration expanded production, communication, cooperation, and cultural exchange while generating unequal gains, environmental pressures, political control, and organized resistance. Local actors adapted global systems rather than simply receiving them.',prompt:'How did communities preserve agency while responding to the benefits and costs of globalization?',takeaways:['Globalization produced different outcomes across places and social groups.','States remained powerful participants in markets, information, health, and culture.','Resistance and adaptation changed global institutions and cultural forms.']},
};
const clone=value=>JSON.parse(JSON.stringify(value));
const replace=(search,replacement)=>{const code=source.replace(search,replacement);assert.notEqual(code,source,`fixture mutation: ${search}`);return code;};
const assertInvalid=(code,rule)=>assert.throws(()=>evaluate(code),error=>{assert.equal(error.name,'Error');assert.match(error.message,/Invalid Unit 9/);assert.match(error.message,rule);return true;});

test('publishes the exact immutable Unit 9 manifest and complete learner contract',()=>{
  assert.ok(source,`Expected ${moduleUrl.pathname} to exist`);const api=evaluate();
  assert.deepEqual(Object.keys(api),['unitId','unitNumber','connectionTimelineMode','locationNumbers','records','unitCards','compareRecords','getById','getByLocation','locationName','getUnitCard']);
  assert.equal(api.unitId,'u9');assert.equal(api.unitNumber,9);assert.equal(api.connectionTimelineMode,'main-event');
  assert.deepEqual(Array.from(api.locationNumbers),Array.from(expectedLocations.keys()));assert.equal(api.records.length,30);
  assert.deepEqual(clone(api.records.map(({id,locationNumber,sequence,title,dateLabel,startYear,endYear,mainEventKey,topicCodes,themeIds,examSkills})=>[id,locationNumber,sequence,title,dateLabel,startYear,endYear,mainEventKey,topicCodes,themeIds,examSkills])),expectedManifest);
  assert.deepEqual([...new Set(api.records.flatMap(record=>record.topicCodes))].sort(),['9.1','9.2','9.3','9.4','9.5','9.6','9.7','9.8','9.9']);
  for(const record of api.records){assert.deepEqual(Object.keys(record),['id','summary','significance','keyPeople','keyTerms','evidence','examConnection','source','locationNumber','sequence','title','dateLabel','startYear','endYear','mainEventKey','topicCodes','themeIds','examSkills','causeStudyPointIds','effectStudyPointIds','relatedStudyPointIds','connectionNotes']);assert.match(record.id,/^apwh-u9-[a-z0-9]+(?:-[a-z0-9]+)*$/);assert.ok(record.summary);assert.ok(record.significance);assert.ok(record.keyPeople.length);assert.ok(record.keyTerms.length);assert.equal(new Set(record.keyTerms.map(term=>term.term)).size,record.keyTerms.length);assert.ok(record.keyTerms.every(term=>term.explanation));assert.ok(record.evidence.length>=2);assert.match(record.examConnection,/^(Analyze|Build|Compare|Contextualize|Evaluate|Explain|Trace)\b/);assert.equal(record.source.id,'amsco-apwh-u9');assert.equal(record.source.locator,L(record.topicCodes));}
});

test('binds exactly three ordered records to each exact location and main event',()=>{
  const api=evaluate();for(const [number,name] of expectedLocations){assert.equal(api.locationName(number),name);const records=api.getByLocation(number);assert.equal(records.length,3);assert.deepEqual(Array.from(records,record=>record.sequence),[1,2,3]);assert.ok(records.every(record=>record.mainEventKey===expectedBindings.get(number)));}
});

test('locks the required Unit 9 content fixtures and historical boundaries',()=>{
  const api=evaluate(),text=id=>JSON.stringify(api.getById(id));
  const content=api.records.map(({id,summary,significance,keyPeople,keyTerms,evidence,examConnection,source})=>({id,summary,significance,keyPeople,keyTerms,evidence,examConnection,source}));
  assert.equal(content.length,expectedContent.length);
  for(let index=0;index<expectedContent.length;index+=1){const actual=content[index],expected=expectedContent[index];for(const field of ['id','summary','significance','keyPeople','keyTerms','evidence','examConnection','source'])assert.deepEqual(clone(actual[field]),expected[field],`${expected.id}: ${field}`);}
  const boundaries=[
    ['apwh-u9-amritsar-high-yield-seeds-input-package',['Amritsar–Punjab is a representative anchor','seeds alone did not produce equal gains','high-yield','irrigation','fertilizer','credit','land','mechanization']],
    ['apwh-u9-amritsar-food-population-environmental-costs',['food','population','water','soil']],
    ['apwh-u9-san-francisco-public-research-digital-infrastructure',['San Francisco is a representative anchor','public','semiconductor','comput']],
    ['apwh-u9-san-francisco-computing-internet-information-costs',['internet','information costs']],
    ['apwh-u9-san-francisco-knowledge-economy-distributed-production',['knowledge','distributed production']],
    ['apwh-u9-guangzhou-market-reform-special-economic-zones',['Deng','special economic zone','state choice']],
    ['apwh-u9-guangzhou-supply-chain-labor-environmental-costs',['supply','labor','environment']],
    ['apwh-u9-ciudad-juarez-border-industrialization',['Border Industrialization Program','before NAFTA']],
    ['apwh-u9-ciudad-juarez-employment-gender-labor-environment',['maquiladora','gender','labor','pollution']],
    ['apwh-u9-beijing-market-reform-political-control',['market reform','political liberalization']],
    ['apwh-u9-beijing-tiananmen-protest-repression',['Tiananmen','repression']],
    ['apwh-u9-beijing-wto-integration-information-control',['WTO','information control','did not cause democratization']],
    ['apwh-u9-washington-bretton-woods-financial-institutions',['Washington, D.C. is a headquarters anchor','the World Bank, IMF, and WTO were distinct institutions','Bretton Woods']],
    ['apwh-u9-washington-institutional-power-benefits-criticism',['voting power','criticism']],
    ['apwh-u9-seattle-coalition-protest-digital-organization',['coalition','internet','labor','environment']],
    ['apwh-u9-seattle-fair-trade-labor-continuing-resistance',['fair trade','resistance']],
    ['apwh-u9-paris-universal-rights-global-norm',['UN','human rights','representative diplomacy anchor']],
    ['apwh-u9-paris-kyoto-burden-sharing-debate',['Kyoto','burden sharing','sovereignty']],
    ['apwh-u9-paris-voluntary-climate-governance-limits',['Paris Agreement','nationally determined contribution','enforcement']],
    ['apwh-u9-geneva-vaccination-smallpox-eradication',['Geneva is a coordination anchor','WHO','vaccination','smallpox']],
    ['apwh-u9-geneva-hiv-treatment-unequal-access',['HIV','unequal access']],
    ['apwh-u9-geneva-polio-ebola-coordination-limits',['polio','Ebola','surveillance','state capacity','resources']],
    ['apwh-u9-seoul-state-supported-cultural-industries',['Seoul is a representative anchor','state support','cultural industr']],
    ['apwh-u9-seoul-digital-platforms-transnational-audiences',['digital','transnational audiences']],
    ['apwh-u9-seoul-hybrid-culture-exports-soft-power',['hybrid','export','soft power','globalization was not synonymous with Americanization']],
  ];
  for(const [id,phrases] of boundaries){const content=text(id);for(const phrase of phrases)assert.ok(content.toLowerCase().includes(phrase.toLowerCase()),`${id}: ${phrase}`);}
  const sanFrancisco=api.getByLocation('70').map(text).join(' ');assert.doesNotMatch(sanFrancisco,/internet (?:was )?invented (?:in|at)|World Wide Web (?:was )?invented (?:in|at)/i);
});

test('provides defensive lookups, comparator tie breakers, generic Task 2 cards, and a locked global',()=>{
  const sandbox=evaluateSandbox(),api=sandbox.APWH_U9_LOCATION_STUDY,descriptor=Object.getOwnPropertyDescriptor(sandbox,'APWH_U9_LOCATION_STUDY');
  assert.deepEqual({enumerable:descriptor.enumerable,configurable:descriptor.configurable,writable:descriptor.writable},{enumerable:true,configurable:false,writable:false});
  assert.equal(api.getById(api.records[0].id),api.records[0]);assert.equal(api.getById('missing'),null);assert.equal(api.locationName('missing'),null);assert.deepEqual(Array.from(api.getByLocation('missing')),[]);
  const local=api.getByLocation('11');local.pop();assert.equal(api.getByLocation('11').length,3);
  const rows=[{sequence:2,startYear:1,endYear:1,id:'z'},{sequence:1,startYear:3,endYear:1,id:'z'},{sequence:1,startYear:2,endYear:3,id:'z'},{sequence:1,startYear:2,endYear:2,id:'z'},{sequence:1,startYear:2,endYear:2,id:'a'}];rows.sort(api.compareRecords);assert.deepEqual(rows.map(row=>[row.sequence,row.startYear,row.endYear,row.id]),[[1,2,2,'a'],[1,2,2,'z'],[1,2,3,'z'],[1,3,1,'z'],[2,1,1,'z']]);
  assert.deepEqual(clone(api.unitCards),expectedUnitCards);for(const [kind,card] of Object.entries(expectedUnitCards)){assert.equal(api.getUnitCard(kind),api.unitCards[kind]);assert.equal(api.getUnitCard(card.id),api.unitCards[kind]);}for(const key of ['missing','toString','constructor','__proto__'])assert.equal(api.getUnitCard(key),null);
  assert.throws(()=>evaluate(source,{APWH_U9_LOCATION_STUDY:{}}),/Invalid Unit 9 global APWH_U9_LOCATION_STUDY: refusing to overwrite existing value/);
});

test('deep freezes every published object and uses the minimum Task 2 graph placeholder',()=>{
  const api=evaluate(),seen=new Set();const deep=value=>{if(value===null||typeof value!=='object'||seen.has(value))return;seen.add(value);assert.equal(Object.isFrozen(value),true);for(const key of Reflect.ownKeys(value))deep(value[key]);};deep(api);
  const [sourceId,targetId,note]=placeholderEdge,sourceRecord=api.getById(sourceId),targetRecord=api.getById(targetId);
  assert.deepEqual(clone(sourceRecord.effectStudyPointIds),[targetId]);assert.deepEqual(clone(targetRecord.causeStudyPointIds),[sourceId]);assert.equal(sourceRecord.connectionNotes[targetId],note);assert.equal(targetRecord.connectionNotes[sourceId],note);
  assert.equal(api.records.reduce((sum,record)=>sum+record.effectStudyPointIds.length,0),1);assert.equal(api.records.reduce((sum,record)=>sum+record.relatedStudyPointIds.length,0),0);
});

test('rejects location, binding, identity, sequence, count, and date drift',()=>{
  assertInvalid(replace("'11':'Food Security & Unequal Inputs · India / Amritsar–Punjab'","'11':'Wrong place'"),/canonical name/);
  assertInvalid(replace("'11':'world-event-11-3'","'11':'world-event-11-4'"),/main-event binding/);
  assertInvalid(replace("'apwh-u9-amritsar-unequal-access-land-consolidation','11',2","'apwh-u9-amritsar-high-yield-seeds-input-package','11',2"),/duplicate record ID/);
  assertInvalid(replace("P('apwh-u9-amritsar-unequal-access-land-consolidation'","P('apwh-u9-amritsar-high-yield-seeds-input-package'"),/duplicate raw record ID/);
  assertInvalid(replace("'apwh-u9-amritsar-unequal-access-land-consolidation','11',2","'apwh-u9-amritsar-unequal-access-land-consolidation','11',1"),/duplicate sequence|exactly three records/);
  assertInvalid(replace("['apwh-u9-amritsar-food-population-environmental-costs'","['apwh-u9-fourth-record','11',4,'Fourth','1991',1991,1991,'world-event-11-3',['9.9'],['GOV'],['Causation']],\n['apwh-u9-amritsar-food-population-environmental-costs'"),/expected exactly 30 records|exactly three records/);
  assertInvalid(replace("'1978–1984',1978,1984","'1978-1984',1978,1984"),/invalid dateLabel/);
  assertInvalid(replace("'1978–1984',1978,1984","'1978–1985',1978,1984"),/invalid dateLabel/);
});

test('rejects missing, invalid, and duplicate taxonomy values',()=>{
  assertInvalid(replace("['9.1','9.3'],['TEC','ENV']","[],['TEC','ENV']"),/missing topicCodes/);
  assertInvalid(replace("['9.1','9.3'],['TEC','ENV']","['9.1','9.1'],['TEC','ENV']"),/duplicate topicCode/);
  assertInvalid(replace("['9.1','9.3'],['TEC','ENV']","['9.0'],['TEC','ENV']"),/invalid topicCode/);
  assertInvalid(replace("['TEC','ENV'],['Contextualization','Causation']","[],['Contextualization','Causation']"),/missing themeIds/);
  assertInvalid(replace("['TEC','ENV'],['Contextualization','Causation']","['TEC','TEC'],['Contextualization','Causation']"),/duplicate themeId/);
  assertInvalid(replace("['TEC','ENV'],['Contextualization','Causation']","['WAR'],['Contextualization','Causation']"),/invalid themeId/);
  assertInvalid(replace("['TEC','ENV'],['Contextualization','Causation']","['TEC','ENV'],[]"),/missing examSkills/);
  assertInvalid(replace("['TEC','ENV'],['Contextualization','Causation']","['TEC','ENV'],['Causation','Causation']"),/duplicate examSkill/);
  assertInvalid(replace("['TEC','ENV'],['Contextualization','Causation']","['TEC','ENV'],['Recall']"),/invalid examSkill/);
});

test('rejects incomplete, non-English, and malformed learner content',()=>{
  assertInvalid(replace("'High-yield wheat and rice varieties increased harvest potential only when farmers could combine them with irrigation, fertilizer, credit, land, and mechanization.'","''"),/summary/);
  assertInvalid(replace("'Amritsar–Punjab is a representative anchor for Green Revolution change, and seeds alone did not produce equal gains because complementary inputs were distributed unevenly.'","'全球化'"),/significance/);
  assertInvalid(replace("'Indian agricultural officials and Punjab farmers','Distributed new varieties and made choices about irrigation, fertilizer, credit, land, and machinery.'","'','Distributed new varieties and made choices about irrigation, fertilizer, credit, land, and machinery.'"),/keyPeople/);
  assertInvalid(replace("'Green Revolution','The spread of high-yield crop varieties together with the inputs and institutions needed to raise agricultural output.'","'Green Revolution',''"),/keyTerms/);
  assertInvalid(replace("['High-yield wheat varieties spread widely in Punjab during the late 1960s.','Tube wells, fertilizer purchases, rural credit, and tractors helped farmers realize higher yields.']","['Only one statement.']"),/evidence/);
  assertInvalid(replace("'Explain causation by linking new seed varieties to the irrigation, fertilizer, credit, land, and mechanization that made them productive.'","''"),/examConnection/);
  assertInvalid(replace("source:{id:'amsco-apwh-u9',locator}","source:{id:'wrong',locator}"),/source/);
  assertInvalid(replace("source:{id:'amsco-apwh-u9',locator}","source:{id:'amsco-apwh-u9',locator,extra:true}"),/source/);
  assertInvalid(replace('validate();',"Object.defineProperty(RAW_RECORDS[0].evidence,'0',{enumerable:false});validate();"),/evidence/);
});

test('rejects null or hostile raw registries, cards, and graph structures with controlled diagnostics',()=>{
  for(const [search,replacement,rule] of [
    ['const LOCATIONS=Object.freeze({','const LOCATIONS=Object.freeze(null); const UNUSED_LOCATIONS=Object.freeze({',/location registry/],
    ['const BINDINGS=Object.freeze({','const BINDINGS=Object.freeze(null); const UNUSED_BINDINGS=Object.freeze({',/location registry/],
    ['const RAW_RECORDS=[','const RAW_RECORDS=null; const UNUSED_RAW_RECORDS=[',/raw records/],
    ['const CONNECTIONS={','const CONNECTIONS=null; const UNUSED_CONNECTIONS={',/connections must contain exactly/],
    ["const CARD_KEYS=['context','synthesis'];","const CARD_KEYS=null; const UNUSED_CARD_KEYS=['context','synthesis'];",/unit cards/],
    ['const UNIT_CARD_MANIFEST={','const UNIT_CARD_MANIFEST=null; const UNUSED_UNIT_CARD_MANIFEST={',/unit cards/],
  ])assertInvalid(replace(search,replacement),rule);
  assertInvalid(replace("'11':'Food Security & Unequal Inputs · India / Amritsar–Punjab'","get '11'(){throw new Error('accessor leaked');}"),/location registry/);
});

test('rejects unresolved, self, duplicate, and malformed graph links',()=>{
  const edge=`['${placeholderEdge[0]}','${placeholderEdge[1]}','${placeholderEdge[2]}']`;
  const unresolved=replace(edge,edge.replace(`'${placeholderEdge[0]}'`,`'apwh-u9-missing-source'`));
  assert.throws(()=>evaluate(unresolved),error=>{assert.equal(error.name,'Error');assert.match(error.message,/Invalid Unit 9 study record apwh-u9-missing-source: unresolved connection/);return true;});
  assertInvalid(replace(edge,edge.replace(`'${placeholderEdge[1]}'`,`'${placeholderEdge[0]}'`)),/self connection/);
  assertInvalid(replace('causal:[','causal:['+edge+','),/duplicate causal connection/);
  const malformed=replace(edge,`['${placeholderEdge[0]}','${placeholderEdge[1]}']`);
  assert.throws(()=>evaluate(malformed),error=>{assert.equal(error.name,'Error');assert.match(error.message,new RegExp(`Invalid Unit 9 study record ${placeholderEdge[0]}: connection row`));return true;});
  assertInvalid(replace(edge,edge.replace(`'${placeholderEdge[0]}'`,`Symbol('bad source')`)),/unresolved connection/);
});

test('rejects malformed generic Task 2 cards',()=>{
  assertInvalid(replace("kind:'context'","kind:'synthesis'"),/card kind/);
  assertInvalid(replace("role:'Unit 9 Context Card'","role:''"),/malformed card/);
  assertInvalid(replace("examSkills:['Contextualization','Causation']","examSkills:['Causation','Causation']"),/card skills/);
  assertInvalid(replace("synthesis:{id:'apwh-u9-synthesis-globalization-benefits-resistance'","synthesis:{id:'apwh-u9-context-accelerating-global-connections'"),/duplicate card ID/);
});

test('validates the graph twice without mutation and never leaks a TypeError',()=>{
  const api=evaluate(replace('validate();','validate();validate();'));assert.equal(api.records.length,30);
  const graphMalformed=replace('validate();',"validate();CONNECTIONS.causal[0][0]='missing';validate();");assert.throws(()=>evaluate(graphMalformed),error=>{assert.equal(error.name,'Error');assert.match(error.message,/Invalid Unit 9/);assert.match(error.message,/unresolved connection/);return true;});
  const malformed=replace('validate();',"STUDY_MANIFEST[0][0]=Symbol('bad');validate();validate();");assert.throws(()=>evaluate(malformed),error=>{assert.equal(error.name,'Error');assert.match(error.message,/Invalid Unit 9/);assert.match(error.message,/invalid stable ID/);return true;});
});
