import assert from 'node:assert/strict';
import test from 'node:test';
import { existsSync, readFileSync } from 'node:fs';
import vm from 'node:vm';

const moduleUrl=new URL('../data/apwh-u8-location-study.js',import.meta.url);
const ledgerUrl=new URL('../docs/data-sources/apwh-u8-location-study-source-ledger.md',import.meta.url);
const source=existsSync(moduleUrl)?readFileSync(moduleUrl,'utf8'):'';
const ledger=existsSync(ledgerUrl)?readFileSync(ledgerUrl,'utf8'):'';
const evaluateSandbox=(code=source,seed={})=>{const sandbox={...seed};sandbox.window=sandbox;vm.runInNewContext(code,sandbox);return sandbox;};
const evaluate=(code=source,seed={})=>evaluateSandbox(code,seed).APWH_U8_LOCATION_STUDY;
const expectedLocations=new Map([
  ['29','Cold War Division · Germany / Berlin'],['40','Soviet Power & Collapse · Soviet Union / Moscow'],['5','Communist Revolution & Transformation · China / Beijing'],['16','Decolonization & Proxy War · Vietnam / Saigon'],['6','Independence, Nonalignment & Development · India / Delhi'],['79','Settler Colonialism & Armed Decolonization · Algeria / Algiers'],['81','Negotiated Independence & Pan-Africanism · Ghana / Accra'],['55','Revolution & Nuclear Brinkmanship · Cuba / Havana'],['21','Oil, Intervention & Revolution · Iran / Tehran'],['82','Apartheid & Democratic Transition · South Africa / Johannesburg'],
]);
const expectedBindings=new Map([
  ['29','world-event-29-8'],['40','world-event-40-3'],['5','world-event-5-5'],['16','world-event-16-0'],['6','world-event-6-3'],['79','world-event-79-1'],['81','world-event-81-0'],['55','world-event-55-2'],['21','world-event-21-1'],['82','world-event-82-0'],
]);
const expectedManifest=[
['apwh-u8-berlin-occupation-ideological-division','29',1,'Occupation Zones and Ideological Division','1945–1948',1945,1948,'world-event-29-8',['8.1','8.2'],['GOV','CDI'],['Contextualization','Causation']],
['apwh-u8-berlin-blockade-airlift-two-germanies','29',2,'Blockade, Airlift, and Two Germanies','1948–1949',1948,1949,'world-event-29-8',['8.2','8.3'],['GOV','TEC'],['Causation']],
['apwh-u8-berlin-wall-nonintervention-reunification','29',3,'Berlin Wall, Soviet Nonintervention, and Reunification','1961–1990',1961,1990,'world-event-29-8',['8.2','8.8','8.9'],['GOV','CDI'],['Causation','CCOT']],
['apwh-u8-moscow-security-buffer-soviet-bloc','40',1,'Security Buffer and the Soviet Bloc','1945–1955',1945,1955,'world-event-40-3',['8.1','8.2'],['GOV'],['Contextualization','Causation']],
['apwh-u8-moscow-detente-arms-afghanistan-strain','40',2,'Détente, Arms, Afghanistan, and Structural Strain','1972–1985',1972,1985,'world-event-40-3',['8.2','8.3','8.8'],['GOV','ECN','TEC'],['Causation','CCOT']],
['apwh-u8-moscow-gorbachev-reform-soviet-dissolution','40',3,"Gorbachev's Reforms and Soviet Dissolution",'1985–1991',1985,1991,'world-event-40-3',['8.8','8.9'],['GOV','ECN'],['Causation']],
['apwh-u8-beijing-civil-war-land-communist-victory','5',1,'Civil War, Land, and Communist Victory','1945–1949',1945,1949,'world-event-5-5',['8.4'],['GOV','SIO'],['Causation']],
['apwh-u8-beijing-great-leap-state-mobilization-famine','5',2,'Great Leap Forward, State Mobilization, and Famine','1958–1962',1958,1962,'world-event-5-5',['8.4'],['GOV','ECN','SIO'],['Causation']],
['apwh-u8-beijing-cultural-revolution-social-upheaval','5',3,'Cultural Revolution and Social Upheaval','1966–1976',1966,1976,'world-event-5-5',['8.4','8.7','8.9'],['GOV','CDI','SIO'],['Causation','CCOT']],
['apwh-u8-saigon-french-return-anticolonial-war','16',1,'French Return and Anticolonial War','1946–1954',1946,1954,'world-event-16-0',['8.5'],['GOV','CDI'],['Contextualization','Causation']],
['apwh-u8-saigon-partition-containment-escalation','16',2,'Partition, Containment, and Escalation','1954–1968',1954,1968,'world-event-16-0',['8.2','8.3'],['GOV'],['Causation']],
['apwh-u8-saigon-withdrawal-reunification-war-costs','16',3,'Withdrawal, Reunification, and War Costs','1968–1975',1968,1975,'world-event-16-0',['8.3','8.9'],['GOV','SIO'],['Causation','CCOT']],
['apwh-u8-delhi-independence-partition-displacement','6',1,'Independence, Partition, and Displacement','1947',1947,1947,'world-event-6-3',['8.5','8.6'],['GOV','CDI','SIO'],['Causation','Comparison']],
['apwh-u8-delhi-nonalignment-foreign-policy-autonomy','6',2,'Nonalignment and Foreign-Policy Autonomy','1955–1961',1955,1961,'world-event-6-3',['8.2','8.6'],['GOV'],['Causation','Comparison']],
['apwh-u8-delhi-five-year-plans-mixed-economy','6',3,'Five-Year Plans and a Mixed Economy','1951–1991',1951,1991,'world-event-6-3',['8.6','8.9'],['ECN','GOV'],['CCOT','Comparison']],
['apwh-u8-algiers-settler-colonialism-blocked-reform','79',1,'Settler Colonialism and Blocked Reform','1945–1954',1945,1954,'world-event-79-1',['8.5'],['GOV','SIO'],['Contextualization','Causation']],
['apwh-u8-algiers-fln-war-counterinsurgency','79',2,'FLN War and French Counterinsurgency','1954–1962',1954,1962,'world-event-79-1',['8.5','8.7'],['GOV','SIO'],['Causation']],
['apwh-u8-algiers-independence-exodus-new-state','79',3,'Independence, Exodus, and the New State','1962',1962,1962,'world-event-79-1',['8.6','8.9'],['GOV','SIO'],['Causation','CCOT']],
['apwh-u8-accra-mass-nationalism-colonial-pressure','81',1,'Mass Nationalism and Colonial Pressure','1947–1951',1947,1951,'world-event-81-0',['8.5'],['GOV','CDI','SIO'],['Contextualization','Causation']],
['apwh-u8-accra-negotiated-independence','81',2,'Negotiated Independence','1951–1957',1951,1957,'world-event-81-0',['8.5'],['GOV'],['Causation','Comparison']],
['apwh-u8-accra-panafricanism-nonaligned-state-building','81',3,'Pan-Africanism, Nonalignment, and State Building','1957–1966',1957,1966,'world-event-81-0',['8.6','8.9'],['GOV','CDI','ECN'],['CCOT','Comparison']],
['apwh-u8-havana-batista-inequality-revolution','55',1,'Batista, Inequality, and Revolution','1952–1959',1952,1959,'world-event-55-2',['8.4','8.7'],['GOV','ECN','SIO'],['Contextualization','Causation']],
['apwh-u8-havana-bay-of-pigs-soviet-alignment','55',2,'Bay of Pigs and Soviet Alignment','1959–1961',1959,1961,'world-event-55-2',['8.2','8.3','8.4'],['GOV'],['Causation']],
['apwh-u8-havana-missile-crisis-nuclear-limits','55',3,'Missile Crisis and the Limits of Nuclear Competition','1962',1962,1962,'world-event-55-2',['8.2','8.3','8.9'],['GOV','TEC'],['Causation','Comparison']],
['apwh-u8-tehran-oil-nationalism-mosaddegh','21',1,'Oil Nationalism and Mosaddegh','1941–1953',1941,1953,'world-event-21-1',['8.6','8.7'],['ECN','GOV'],['Contextualization','Causation']],
['apwh-u8-tehran-coup-shah-authoritarian-alignment','21',2,"The 1953 Coup and the Shah's Alignment",'1953–1963',1953,1963,'world-event-21-1',['8.2','8.6'],['GOV','ECN'],['Causation']],
['apwh-u8-tehran-white-revolution-islamic-revolution','21',3,'White Revolution and the 1979 Islamic Revolution','1963–1979',1963,1979,'world-event-21-1',['8.6','8.7','8.9'],['GOV','CDI','SIO'],['Causation','CCOT']],
['apwh-u8-johannesburg-apartheid-legal-order','82',1,'Apartheid as a Legal Order','1948–1960',1948,1960,'world-event-82-0',['8.7'],['GOV','SIO'],['Contextualization','Causation']],
['apwh-u8-johannesburg-resistance-repression','82',2,'Organized Resistance and State Repression','1950–1989',1950,1989,'world-event-82-0',['8.7'],['GOV','SIO'],['Causation']],
['apwh-u8-johannesburg-pressure-negotiation-democratic-transition','82',3,'International Pressure, Negotiation, and Democratic Transition','1985–1994',1985,1994,'world-event-82-0',['8.7','8.9'],['GOV','SIO'],['Causation','CCOT']],
];
const P=(id,summary,significance,person,role,term,explanation,evidence,examConnection,locator)=>({id,summary,significance,keyPeople:[{name:person,role}],keyTerms:[{term,explanation}],evidence,examConnection,source:{id:'amsco-apwh-u8',locator}});
const L=topics=>`AMSCO AP World History, Unit 8, ${topics.length===1?'Topic':'Topics'} ${topics.length===1?topics[0]:topics.length===2?topics.join(' and '):`${topics.slice(0,-1).join(', ')}, and ${topics.at(-1)}`}`;
const expectedContent=[
// Exact literal learner-content fixtures are intentionally independent of the production module.
P('apwh-u8-berlin-occupation-ideological-division','Allied occupation divided Germany and Berlin into zones as wartime cooperation gave way to competing political and economic systems.','Broad Soviet security aims help explain the eastern buffer, while specific choices over German recovery and currency reform produced distinct confrontations.','Allied occupation authorities','Administered separate zones and promoted rival postwar orders.','occupation zones','Areas of Germany and Berlin administered by the victorious Allied powers after World War II.',['Germany and Berlin were each divided among American, British, French, and Soviet authorities.','Western zones moved toward economic coordination and currency reform in 1948.'],'Contextualize the Cold War by separating broad Soviet security aims from the specific decisions that triggered the Berlin blockade.',L(['8.1','8.2'])),
P('apwh-u8-berlin-blockade-airlift-two-germanies','The Soviet Union blockaded western land access to Berlin, and the Western Allies supplied the city by air before two German states emerged.','The crisis tested containment without direct superpower war and hardened the political division of Germany.','Joseph Stalin and Western Allied leaders','Made blockade, airlift, and occupation-policy decisions during the crisis.','Berlin Airlift','The Western air supply operation that sustained West Berlin during the Soviet blockade.',['The blockade restricted western land access from June 1948 to May 1949.','American and British aircraft delivered food and fuel to West Berlin.'],'Explain how the blockade and airlift caused political consolidation while distinguishing them from general Soviet security policy.',L(['8.2','8.3'])),
P('apwh-u8-berlin-wall-nonintervention-reunification','East Germany built the Berlin Wall to restrict emigration; decades later Soviet nonintervention allowed peaceful pressure and diplomacy to culminate in reunification.','The Wall embodied Cold War division, while its opening and reunification demonstrate change in Soviet coercive policy.','Mikhail Gorbachev and German political leaders','Accepted negotiations and refrained from a Soviet military intervention against political change.','Berlin Wall','The fortified barrier erected in 1961 that divided East and West Berlin until 1989.',['East German authorities erected the Wall in August 1961.','Germany formally reunified in October 1990 after the Wall opened in 1989.'],'Trace continuity and change from coercive division to Soviet nonintervention and negotiated reunification.',L(['8.2','8.8','8.9'])),
P('apwh-u8-moscow-security-buffer-soviet-bloc','The Soviet Union installed or supported communist governments across Eastern Europe and organized them into a strategic bloc.','The buffer reflected security fears after invasion and also extended Soviet political control, helping produce a bipolar order.','Joseph Stalin and Eastern European communist parties','Consolidated Soviet-aligned governments across Eastern Europe.','Warsaw Pact','The Soviet-led military alliance established in 1955 in Eastern Europe.',['Communist governments dominated Poland, Hungary, Czechoslovakia, and other Eastern European states.','The Warsaw Pact institutionalized Soviet military leadership in 1955.'],'Contextualize Soviet expansion through both postwar security concerns and the exercise of imperial power.',L(['8.1','8.2'])),
P('apwh-u8-moscow-detente-arms-afghanistan-strain','Détente reduced some tensions, but arms costs, the Afghanistan war, economic stagnation, and political rigidity placed mounting pressure on the Soviet system.','These economic, military, and political problems interacted over time rather than operating as a single automatic cause of collapse.','Leonid Brezhnev and Soviet officials','Pursued détente, military competition, and intervention while presiding over stagnation.','détente','A period of reduced Cold War tensions and negotiated limits between the superpowers.',['The United States and Soviet Union signed SALT I in 1972.','The Soviet military entered Afghanistan in 1979 and fought a costly war.'],'Build a multicausal argument about interacting strains rather than a single automatic cause of Soviet collapse.',L(['8.2','8.3','8.8'])),
P('apwh-u8-moscow-gorbachev-reform-soviet-dissolution','Gorbachev introduced glasnost and perestroika, reduced coercive support for Eastern European regimes, and confronted nationalist and economic pressures.','Reform widened political participation but weakened established controls amid interacting economic, national, and institutional strains.','Mikhail Gorbachev','Promoted openness, restructuring, and reduced reliance on force in the Soviet bloc.','glasnost and perestroika','Policies of political openness and economic restructuring introduced under Gorbachev.',['Eastern European communist governments fell in 1989 without a Soviet military crackdown.','The Soviet Union dissolved into independent republics in December 1991.'],'Explain how reform and withdrawal of coercive support interacted with longer-term strains to dissolve the Soviet Union.',L(['8.8','8.9'])),
P('apwh-u8-beijing-civil-war-land-communist-victory','Chinese Communists gained support through land reform, rural organization, nationalism, and effective forces while Nationalist weakness deepened after war.','Communist victory grew from several political and social causes, not from later Maoist programs projected backward.','Mao Zedong and Chiang Kai-shek','Led the Communist and Nationalist sides in the renewed civil war.','Chinese Civil War','The struggle that ended with Communist victory on the mainland and Nationalist retreat to Taiwan.',['Communist forces drew support from many rural communities through land policies.','Mao proclaimed the People’s Republic of China in Beijing in October 1949.'],'Use land policy, nationalism, and Nationalist weakness as distinct evidence in a multicausal explanation.',L(['8.4'])),
P('apwh-u8-beijing-great-leap-state-mobilization-famine','The Great Leap Forward used communes and state production targets to accelerate industrial and agricultural transformation.','Coercive mobilization and distorted reporting contributed to catastrophic famine; this program was distinct from the later Cultural Revolution.','Mao Zedong and commune officials','Directed mass mobilization and enforced ambitious production targets.','Great Leap Forward','The campaign beginning in 1958 to collectivize agriculture and rapidly expand production.',['Rural households were reorganized into large people’s communes.','Inflated harvest reports and state procurement worsened a famine that killed millions.'],'Explain how policy incentives and coercive institutions caused famine without treating every communist campaign as interchangeable.',L(['8.4'])),
P('apwh-u8-beijing-cultural-revolution-social-upheaval','Mao mobilized Red Guards against alleged enemies, disrupting schools, institutions, cultural life, and families during the Cultural Revolution.','The campaign renewed Maoist power through ideological struggle and mass upheaval, differing in methods and targets from the Great Leap.','Mao Zedong and the Red Guards','Mobilized young people to attack alleged bourgeois and counterrevolutionary influences.','Cultural Revolution','A 1966–1976 campaign of ideological purification and political struggle in China.',['Red Guards attacked officials, teachers, and cultural objects.','Schools and universities closed or operated irregularly during major phases of upheaval.'],'Trace change across communist programs by distinguishing Cultural Revolution ideology and targets from Great Leap production policies.',L(['8.4','8.7','8.9'])),
P('apwh-u8-saigon-french-return-anticolonial-war','France attempted to restore colonial rule after World War II, while the Viet Minh fought an anticolonial war for Vietnamese independence.','The First Indochina War was fundamentally a decolonization struggle even as Cold War alignments increasingly shaped outside support.','Ho Chi Minh and the Viet Minh','Led organized resistance to renewed French colonial rule.','First Indochina War','The 1946–1954 anticolonial war between French forces and the Viet Minh.',['Ho Chi Minh declared Vietnamese independence in 1945.','The French defeat at Dien Bien Phu in 1954 ended the major phase of colonial war.'],'Contextualize Vietnamese agency and distinguish anti-French decolonization from the later United States-centered proxy war.',L(['8.5'])),
P('apwh-u8-saigon-partition-containment-escalation','The Geneva settlement temporarily partitioned Vietnam, while containment policy and rival Vietnamese governments led to escalating external intervention.','The conflict became a major Cold War proxy war, but Vietnamese political goals and choices remained central; Saigon is a representative national anchor.','Ngo Dinh Diem and Vietnamese revolutionary leaders','Led rival governments and movements amid expanding foreign involvement.','Geneva Accords','The 1954 agreements that temporarily divided Vietnam near the seventeenth parallel pending elections.',['South Vietnam established its capital at Saigon after the Geneva settlement.','The United States greatly expanded troop deployments after 1964.'],'Explain escalation through containment and Vietnamese agency rather than presenting Vietnam only as a superpower chessboard.',L(['8.2','8.3'])),
P('apwh-u8-saigon-withdrawal-reunification-war-costs','Vietnamese communist forces survived United States escalation, while antiwar pressure and policy changes contributed to American withdrawal before reunification.','The war imposed immense human costs and ended with a unified communist Vietnam, showing limits to military containment.','Vietnamese forces and United States policymakers','Continued the war, negotiated withdrawal, and contested control of South Vietnam.','Vietnamization','The United States policy of transferring more combat responsibility to South Vietnamese forces.',['The Paris Peace Accords were signed in 1973 and United States combat forces withdrew.','Saigon was renamed Ho Chi Minh City after reunification in 1976.'],'Trace how Vietnamese endurance, domestic pressure, and withdrawal policy contributed to reunification and changing views of war.',L(['8.3','8.9'])),
P('apwh-u8-delhi-independence-partition-displacement','British India became independent as India and Pakistan, while Partition produced mass migration and violence, especially across Punjab and Bengal.','Sovereignty arrived with territorial division and displacement; Delhi is a representative national anchor rather than the sole Partition site.','Jawaharlal Nehru and Muhammad Ali Jinnah','Led major political movements shaping independence and Partition.','Partition of India','The 1947 division of British India into India and Pakistan.',['Punjab and Bengal were principal Partition regions.','Millions crossed new borders and large numbers died in communal violence.'],'Compare political independence with its social costs, stating that Delhi is a representative national anchor.',L(['8.5','8.6'])),
P('apwh-u8-delhi-nonalignment-foreign-policy-autonomy','India joined other postcolonial states in seeking foreign-policy autonomy outside formal United States or Soviet blocs.','Indian leaders argued that nonalignment was not neutrality; they cooperated selectively while defending sovereignty and development priorities.','Jawaharlal Nehru','Advocated nonalignment and helped convene Afro-Asian cooperation.','Non-Aligned Movement','A coalition seeking autonomy from formal alignment with either Cold War superpower bloc.',['India participated in the Bandung Conference of 1955.','Nehru helped launch the Non-Aligned Movement at Belgrade in 1961.'],'Compare nonalignment with neutrality by showing active diplomacy, selective cooperation, and defense of sovereignty.',L(['8.2','8.6'])),
P('apwh-u8-delhi-five-year-plans-mixed-economy','Independent India used Five-Year Plans, public-sector investment, and regulated private enterprise to pursue development in a mixed economy.','Planning expressed economic sovereignty while producing gains and persistent constraints across four decades.','Indian Planning Commission','Set national investment priorities across public and private sectors.','mixed economy','An economy combining state planning and public enterprises with private ownership and markets.',['India launched its First Five-Year Plan in 1951.','The state invested heavily in infrastructure and large industries while private firms continued operating.'],'Compare India’s mixed economy with both capitalist and communist development strategies and trace results over time.',L(['8.6','8.9'])),
P('apwh-u8-algiers-settler-colonialism-blocked-reform','French Algeria combined European settler political privilege with restrictions and inequality for the Muslim majority, while reform remained blocked.','Settler institutions and denied political equality created conflict through historical choices, not ethnic inevitability.','French settlers and Algerian reformers','Contested citizenship, representation, land, and political equality.','settler colonialism','A colonial system in which settlers establish durable political and economic dominance over an indigenous population.',['European settlers held disproportionate political power in French Algeria.','The 1945 Setif violence and repression exposed the limits of colonial reform.'],'Contextualize armed revolt through settler privilege and blocked reform while rejecting ethnic inevitability.',L(['8.5'])),
P('apwh-u8-algiers-fln-war-counterinsurgency','The FLN launched an armed independence struggle, while France used mass counterinsurgency, detention, and torture to preserve Algeria.','The war internationalized decolonization and revealed the coercive costs of maintaining settler colonial rule.','National Liberation Front and French army','Waged insurgency and counterinsurgency across Algeria.','FLN','The National Liberation Front that organized the Algerian independence struggle.',['The FLN began coordinated attacks in November 1954.','French forces used systematic detention and torture during the Battle of Algiers.'],'Use specific insurgency and counterinsurgency evidence to explain escalation without erasing civilian choices and costs.',L(['8.5','8.7'])),
P('apwh-u8-algiers-independence-exodus-new-state','The Evian Accords ended the war, independence prompted a large settler exodus, and the FLN built a new sovereign state.','Decolonization transferred authority but also produced displacement and new struggles over institutions and political inclusion.','Ahmed Ben Bella and FLN leaders','Led the early independent Algerian state after negotiated French withdrawal.','Evian Accords','The 1962 agreements that established a ceasefire and path to Algerian independence.',['Algerian voters approved independence in 1962.','Most European settlers left Algeria around independence.'],'Trace continuity and change from colonial exclusion through exodus to postcolonial state building.',L(['8.6','8.9'])),
P('apwh-u8-accra-mass-nationalism-colonial-pressure','Mass organizing, strikes, protests, and elections increased pressure on British colonial rule in the Gold Coast.','Independence resulted from sustained African mobilization and institutional bargaining, not from Britain simply granting freedom.','Kwame Nkrumah and Convention People’s Party activists','Mobilized mass support through Positive Action and electoral politics.','Positive Action','The Convention People’s Party campaign of strikes and nonviolent protest for self-government.',['The 1948 Accra riots exposed widespread economic and political grievances.','The Convention People’s Party won the 1951 election while Nkrumah was imprisoned.'],'Explain how popular pressure and electoral victories shifted colonial bargaining power.',L(['8.5'])),
P('apwh-u8-accra-negotiated-independence','Electoral victories and constitutional negotiations transferred increasing authority to African leaders before Ghanaian independence.','Negotiation worked because organized nationalism had altered political power; independence was not simply granted.','Kwame Nkrumah and British colonial officials','Negotiated constitutional change after repeated nationalist election victories.','Ghanaian independence','The 1957 transfer of sovereignty that made Ghana the first sub-Saharan African colony to gain independence in this wave.',['Nkrumah became leader of government after the 1951 election.','The Gold Coast became independent Ghana on 6 March 1957.'],'Compare Ghana’s negotiated route with armed decolonization while preserving the role of mass pressure.',L(['8.5'])),
P('apwh-u8-accra-panafricanism-nonaligned-state-building','Nkrumah promoted Pan-African unity and nonalignment while investing in infrastructure and expanding the postcolonial state.','Ambitious development and continental leadership coexisted with debt, political centralization, and domestic tensions.','Kwame Nkrumah','Promoted African unity, nonalignment, and state-led development.','Pan-Africanism','A movement advocating solidarity and political cooperation among African peoples and states.',['Accra hosted the 1958 All-African Peoples’ Conference.','The Volta River project expanded electricity and industrial capacity while increasing financial pressures.'],'Compare Ghanaian state building across political autonomy, infrastructure gains, and tensions over centralization and debt.',L(['8.6','8.9'])),
P('apwh-u8-havana-batista-inequality-revolution','Batista’s dictatorship combined repression with sharp inequalities, while a broad revolutionary coalition fought to remove his regime.','The revolution grew from political exclusion, rural and urban grievances, and organized opposition before later communist alignment.','Fulgencio Batista and Fidel Castro','Led the dictatorship and a revolutionary coalition contesting it.','Cuban Revolution','The movement that overthrew Batista and brought Castro’s coalition to power in 1959.',['Batista seized power in a 1952 coup and canceled elections.','Rebel forces and urban opposition compelled Batista to flee in January 1959.'],'Contextualize the revolution through inequality and repression without collapsing it into the later missile crisis.',L(['8.4','8.7'])),
P('apwh-u8-havana-bay-of-pigs-soviet-alignment','Revolutionary reforms and conflict with the United States deepened Cuban-Soviet ties, while the Bay of Pigs invasion strengthened security fears.','Failed intervention pushed Cuba toward firmer Soviet alignment but did not make every later decision inevitable.','Fidel Castro and John F. Kennedy','Led Cuba and the United States during confrontation and alignment.','Bay of Pigs invasion','The failed 1961 invasion of Cuba by United States-backed Cuban exiles.',['Cuba nationalized major properties after the revolution.','Cuban forces defeated the Bay of Pigs invasion in April 1961.'],'Explain Soviet alignment through reforms, intervention, and security fears while distinguishing it from the 1959 revolution.',L(['8.2','8.3','8.4'])),
P('apwh-u8-havana-missile-crisis-nuclear-limits','Soviet missiles in Cuba led the United States to impose a naval quarantine, producing tense bargaining and reciprocal concessions.','The crisis demonstrated nuclear brinkmanship and restraint because leaders negotiated rather than allowing escalation to become automatic war.','Nikita Khrushchev and John F. Kennedy','Bargained over missiles, quarantine, and security guarantees during the crisis.','Cuban Missile Crisis','The October 1962 confrontation over Soviet nuclear missiles deployed in Cuba.',['Kennedy announced a naval quarantine rather than an immediate air strike.','The Soviet Union removed missiles from Cuba as the United States pledged not to invade and secretly agreed to remove missiles from Turkey.'],'Compare coercion and restraint by using missiles, quarantine, bargaining, and reciprocal concessions as evidence.',L(['8.2','8.3','8.9'])),
P('apwh-u8-tehran-oil-nationalism-mosaddegh','Iranian nationalists challenged foreign control by nationalizing oil under Prime Minister Mosaddegh, provoking a confrontation with Britain.','Oil linked sovereignty and development to anticolonial nationalism while domestic coalitions remained contested.','Mohammad Mosaddegh','Led oil nationalization and defended parliamentary authority.','Anglo-Iranian Oil Company','The British-controlled company whose assets Iran nationalized in 1951.',['Iran’s parliament voted to nationalize the oil industry in 1951.','Britain organized an oil boycott and sought foreign support against Mosaddegh.'],'Contextualize nationalization as a sovereignty claim shaped by foreign ownership and domestic constitutional politics.',L(['8.6','8.7'])),
P('apwh-u8-tehran-coup-shah-authoritarian-alignment','An Anglo-American covert intervention helped overthrow Mosaddegh in 1953, after which the shah strengthened authoritarian rule and Western alignment.','The coup tied Cold War intervention to oil interests and damaged the legitimacy of the shah’s restored power.','Mohammad Reza Shah Pahlavi and intelligence services','Consolidated monarchical power after supporting the removal of Mosaddegh.','1953 Iranian coup','The operation backed by British and United States intelligence that removed Prime Minister Mosaddegh.',['Operation Ajax supported propaganda, political pressure, and forces against Mosaddegh.','After the coup, the shah expanded security institutions and close ties with the United States.'],'Explain the coup through intersecting oil, Cold War, and domestic political conflicts.',L(['8.2','8.6'])),
P('apwh-u8-tehran-white-revolution-islamic-revolution','The shah’s White Revolution pursued land, education, and social reforms while authoritarian exclusion and uneven outcomes energized diverse opposition that overthrew him in 1979.','The Islamic Revolution was not merely a religious reaction to modernization; repression, inequality, nationalism, and competing political visions interacted.','Mohammad Reza Shah Pahlavi and Ayatollah Khomeini','Promoted state reform and led a broad revolutionary opposition from exile.','White Revolution','The shah’s reform program beginning in 1963, including land redistribution and expanded education.',['The shah’s government used SAVAK to repress political opposition.','Strikes and mass demonstrations brought together religious, liberal, leftist, and nationalist opponents in 1978–1979.'],'Construct a multicausal explanation linking reform, exclusion, repression, and diverse opposition rather than reducing 1979 to religion alone.',L(['8.6','8.7','8.9'])),
P('apwh-u8-johannesburg-apartheid-legal-order','South Africa’s government built apartheid through laws regulating racial classification, residence, movement, work, and political rights.','Apartheid was an administered state system rather than only private prejudice; Johannesburg is a representative national anchor.','National Party government','Codified and enforced racial separation and white political supremacy.','apartheid','The legally enforced system of racial classification, segregation, and white minority rule in South Africa.',['The Population Registration Act classified people by race in 1950.','Pass laws and the Group Areas Act restricted movement and residence.'],'Contextualize apartheid through legal and administrative mechanisms, noting that Johannesburg is a representative national anchor.',L(['8.7'])),
P('apwh-u8-johannesburg-resistance-repression','The ANC and allied movements used protest, labor action, civic organization, and later armed struggle while the state answered with bans, arrests, and violence.','Resistance changed form under repression and remained rooted in organized African political agency.','African National Congress activists','Organized campaigns against apartheid despite banning, imprisonment, and state violence.','Defiance Campaign','The 1952 mass campaign of deliberate noncompliance with apartheid laws.',['The ANC helped organize the Defiance Campaign in 1952.','Police killed protesters at Sharpeville in 1960, and the government banned the ANC.'],'Trace continuity and change across nonviolent protest, labor and civic action, armed struggle, and repression.',L(['8.7'])),
P('apwh-u8-johannesburg-pressure-negotiation-democratic-transition','Labor and civic mobilization, international sanctions, economic pressure, and negotiations weakened apartheid and produced democratic elections.','Transition resulted from interacting internal and external pressures plus political bargaining, not from one leader acting alone.','Nelson Mandela and F. W. de Klerk','Negotiated the dismantling of apartheid and a democratic constitutional transition.','democratic transition','The negotiated replacement of apartheid rule with universal-suffrage government.',['International sanctions and divestment increased pressure during the 1980s.','Nelson Mandela was released in 1990 and South Africa held multiracial elections in 1994.'],'Explain the 1994 transition through labor, civic action, sanctions, negotiation, and leadership without making any one factor sufficient.',L(['8.7','8.9'])),
];

const clone=value=>JSON.parse(JSON.stringify(value));
const replace=(search,replacement)=>{const code=source.replace(search,replacement);assert.notEqual(code,source,`fixture mutation: ${search}`);return code;};
const assertInvalid=(code,rule)=>assert.throws(()=>evaluate(code),error=>{assert.match(error.message,/Invalid Unit 8/);assert.match(error.message,rule);assert.notEqual(error.name,'TypeError');return true;});

test('publishes the exact immutable Unit 8 manifest and learner content',()=>{
  assert.ok(source,`Expected ${moduleUrl.pathname} to exist`);const api=evaluate();
  assert.deepEqual(Object.keys(api),['unitId','unitNumber','connectionTimelineMode','locationNumbers','records','unitCards','compareRecords','getById','getByLocation','locationName','getUnitCard']);
  assert.equal(api.unitId,'u8');assert.equal(api.unitNumber,8);assert.equal(api.connectionTimelineMode,'main-event');
  assert.deepEqual(Array.from(api.locationNumbers),Array.from(expectedLocations.keys()));assert.equal(api.records.length,30);
  assert.deepEqual(clone(api.records.map(({id,locationNumber,sequence,title,dateLabel,startYear,endYear,mainEventKey,topicCodes,themeIds,examSkills})=>[id,locationNumber,sequence,title,dateLabel,startYear,endYear,mainEventKey,topicCodes,themeIds,examSkills])),expectedManifest);
  assert.deepEqual(clone(api.records.map(({id,summary,significance,keyPeople,keyTerms,evidence,examConnection,source})=>({id,summary,significance,keyPeople,keyTerms,evidence,examConnection,source}))),expectedContent);
  assert.deepEqual([...new Set(api.records.flatMap(record=>record.topicCodes))].sort(),['8.1','8.2','8.3','8.4','8.5','8.6','8.7','8.8','8.9']);
  for(const record of api.records){assert.match(record.id,/^apwh-u8-[a-z0-9]+(?:-[a-z0-9]+)*$/);assert.ok(record.themeIds.length);assert.ok(record.examSkills.length);assert.equal(record.source.locator,L(record.topicCodes));}
});

test('binds exactly three ordered records to each exact location and main event',()=>{
  const api=evaluate();for(const [number,name] of expectedLocations){assert.equal(api.locationName(number),name);const records=api.getByLocation(number);assert.equal(records.length,3);assert.deepEqual(Array.from(records,record=>record.sequence),[1,2,3]);assert.ok(records.every(record=>record.mainEventKey===expectedBindings.get(number)));}
});

test('provides defensive lookups, comparator tie breakers, cards, and global descriptors',()=>{
  const sandbox=evaluateSandbox(),api=sandbox.APWH_U8_LOCATION_STUDY,descriptor=Object.getOwnPropertyDescriptor(sandbox,'APWH_U8_LOCATION_STUDY');
  assert.deepEqual({enumerable:descriptor.enumerable,configurable:descriptor.configurable,writable:descriptor.writable},{enumerable:true,configurable:false,writable:false});
  assert.equal(api.getById(api.records[0].id),api.records[0]);assert.equal(api.getById('missing'),null);assert.equal(api.locationName('missing'),null);assert.deepEqual(Array.from(api.getByLocation('missing')),[]);
  const local=api.getByLocation('29');local.pop();assert.equal(api.getByLocation('29').length,3);
  const rows=[{sequence:2,startYear:1,endYear:1,id:'z'},{sequence:1,startYear:3,endYear:1,id:'z'},{sequence:1,startYear:2,endYear:3,id:'z'},{sequence:1,startYear:2,endYear:2,id:'z'},{sequence:1,startYear:2,endYear:2,id:'a'}];rows.sort(api.compareRecords);assert.deepEqual(rows.map(row=>[row.sequence,row.startYear,row.endYear,row.id]),[[1,2,2,'a'],[1,2,2,'z'],[1,2,3,'z'],[1,3,1,'z'],[2,1,1,'z']]);
  assert.ok(api.getUnitCard('context'));assert.equal(api.getUnitCard(api.unitCards.context.id),api.unitCards.context);for(const key of ['missing','toString','constructor','__proto__'])assert.equal(api.getUnitCard(key),null);
  assert.throws(()=>evaluate(source,{APWH_U8_LOCATION_STUDY:{}}),/Invalid Unit 8 global APWH_U8_LOCATION_STUDY: refusing to overwrite existing value/);
});

test('deep freezes every published object and defensive array',()=>{
  const api=evaluate(),seen=new Set();const deep=value=>{if(value===null||typeof value!=='object'||seen.has(value))return;seen.add(value);assert.equal(Object.isFrozen(value),true);for(const key of Reflect.ownKeys(value))deep(value[key]);};deep(api);
  for(const record of api.records){assert.ok(Object.isFrozen(record.topicCodes));assert.ok(Object.isFrozen(record.themeIds));assert.ok(Object.isFrozen(record.examSkills));assert.ok(Object.isFrozen(record.keyPeople));assert.ok(Object.isFrozen(record.keyTerms));assert.ok(Object.isFrozen(record.evidence));assert.ok(Object.isFrozen(record.source));}
});

test('keeps the exact required Unit 8 boundary ideas in their relevant learner fixtures',()=>{
  const content=JSON.stringify(expectedContent);for(const boundary of ['nonalignment was not neutrality','Punjab and Bengal were principal Partition regions','Delhi is a representative national anchor','Johannesburg is a representative national anchor','Saigon was renamed Ho Chi Minh City after reunification','interacting strains rather than a single automatic cause'])assert.ok(content.includes(boundary),boundary);
});

test('rejects location, binding, identity, sequence, count, date, and taxonomy drift',()=>{
  assertInvalid(replace("'29':'Cold War Division · Germany / Berlin'","'29':'Wrong place'"),/canonical name/);
  assertInvalid(replace("'29':'world-event-29-8'","'29':'world-event-29-9'"),/main-event binding/);
  assertInvalid(replace("'apwh-u8-berlin-blockade-airlift-two-germanies','29',2","'apwh-u8-berlin-occupation-ideological-division','29',2"),/duplicate record ID/);
  assertInvalid(replace("P('apwh-u8-berlin-blockade-airlift-two-germanies'","P('apwh-u8-berlin-occupation-ideological-division'"),/duplicate raw record ID/);
  assertInvalid(replace("'apwh-u8-berlin-blockade-airlift-two-germanies','29',2","'apwh-u8-berlin-blockade-airlift-two-germanies','29',1"),/duplicate sequence|exactly three records/);
  assertInvalid(replace("['apwh-u8-berlin-wall-nonintervention-reunification'","['apwh-u8-fourth-record','29',4,'Fourth','1991',1991,1991,'world-event-29-8',['8.9'],['GOV'],['Causation']],\n['apwh-u8-berlin-wall-nonintervention-reunification'"),/expected exactly 30 records|exactly three records/);
  assertInvalid(replace("'1948–1949',1948,1949","'1948-1949',1948,1949"),/invalid dateLabel/);
  assertInvalid(replace("'1948–1949',1948,1949","'1948–1950',1948,1949"),/invalid dateLabel/);
  assertInvalid(replace("['8.2','8.3'],['GOV','TEC']","['8.2','8.2'],['GOV','TEC']"),/duplicate topicCode/);
  assertInvalid(replace("['8.2','8.3'],['GOV','TEC']","['8.0'],['GOV','TEC']"),/invalid topicCode/);
  assertInvalid(replace("['GOV','TEC'],['Causation']","['GOV','GOV'],['Causation']"),/duplicate themeId/);
  assertInvalid(replace("['GOV','TEC'],['Causation']","['WAR'],['Causation']"),/invalid themeId/);
  assertInvalid(replace("['GOV','TEC'],['Causation']","['GOV','TEC'],['Causation','Causation']"),/duplicate examSkill/);
  assertInvalid(replace("['GOV','TEC'],['Causation']","['GOV','TEC'],['Recall']"),/invalid examSkill/);
});

test('rejects incomplete, non-English, and malformed learner content',()=>{
  assertInvalid(replace("'Allied occupation divided Germany and Berlin into zones as wartime cooperation gave way to competing political and economic systems.'","''"),/summary/);
  assertInvalid(replace("'Broad Soviet security aims help explain the eastern buffer, while specific choices over German recovery and currency reform produced distinct confrontations.'","'帝国主义'"),/significance/);
  assertInvalid(replace("'Allied occupation authorities','Administered separate zones and promoted rival postwar orders.'","'','Administered separate zones and promoted rival postwar orders.'"),/keyPeople/);
  assertInvalid(replace("'occupation zones','Areas of Germany and Berlin administered by the victorious Allied powers after World War II.'","'occupation zones',''"),/keyTerms/);
  assertInvalid(replace("['Germany and Berlin were each divided among American, British, French, and Soviet authorities.','Western zones moved toward economic coordination and currency reform in 1948.']","['Only one statement.']"),/evidence/);
  assertInvalid(replace("'Contextualize the Cold War by separating broad Soviet security aims from the specific decisions that triggered the Berlin blockade.'","''"),/examConnection/);
  assertInvalid(replace("source:{id:'amsco-apwh-u8',locator}","source:{id:'wrong',locator}"),/source/);
  assertInvalid(replace("source:{id:'amsco-apwh-u8',locator}","source:{id:'amsco-apwh-u8',locator,extra:true}"),/source/);
  assertInvalid(replace('validate();',"Object.defineProperty(RAW_RECORDS[0].evidence,'0',{enumerable:false});validate();"),/evidence/);
});

test('rejects null or hostile ordinary-data structures with controlled Unit 8 diagnostics',()=>{
  for(const [search,replacement,rule] of [
    ['const LOCATIONS=Object.freeze({','const LOCATIONS=Object.freeze(null); const UNUSED_LOCATIONS=Object.freeze({',/location registry/],
    ['const BINDINGS=Object.freeze({','const BINDINGS=Object.freeze(null); const UNUSED_BINDINGS=Object.freeze({',/location registry/],
    ['const RAW_RECORDS=[','const RAW_RECORDS=null; const UNUSED_RAW_RECORDS=[',/raw records/],
    ['const CONNECTIONS={','const CONNECTIONS=null; const UNUSED_CONNECTIONS={',/connections must contain exactly/],
  ])assertInvalid(replace(search,replacement),rule);
  assertInvalid(replace("'29':'Cold War Division · Germany / Berlin'","get '29'(){throw new Error('accessor leaked');}"),/location registry/);
});

test('rejects null card registries with controlled Unit 8 diagnostics',()=>{
  assertInvalid(replace("const CARD_KEYS=['context','synthesis'];","const CARD_KEYS=null; const UNUSED_CARD_KEYS=['context','synthesis'];"),/unit cards must contain exactly/);
  assertInvalid(replace('const UNIT_CARD_MANIFEST={','const UNIT_CARD_MANIFEST=null; const UNUSED_UNIT_CARD_MANIFEST={'),/unit cards must contain exactly/);
});

test('rejects unresolved, self, duplicate, and malformed graph links',()=>{
  const edge="['apwh-u8-berlin-occupation-ideological-division','apwh-u8-berlin-blockade-airlift-two-germanies','Occupation policies and Western currency reform triggered the Soviet blockade; the Allied airlift sustained West Berlin and hardened Germany’s political division.']";
  assertInvalid(replace(edge,"['missing','apwh-u8-berlin-blockade-airlift-two-germanies','Occupation policies and Western currency reform triggered the Soviet blockade; the Allied airlift sustained West Berlin and hardened Germany’s political division.']"),/unresolved connection/);
  assertInvalid(replace(edge,"['apwh-u8-berlin-occupation-ideological-division','apwh-u8-berlin-occupation-ideological-division','Occupation policies and Western currency reform triggered the Soviet blockade; the Allied airlift sustained West Berlin and hardened Germany’s political division.']"),/self connection/);
  assertInvalid(replace('causal:[','causal:['+edge+','),/duplicate causal connection/);
  assertInvalid(replace(edge,"['apwh-u8-berlin-occupation-ideological-division','apwh-u8-berlin-blockade-airlift-two-germanies']"),/connection row/);
});

test('validates the graph twice without mutation and never leaks a TypeError',()=>{
  const api=evaluate(replace('validate();','validate();validate();'));assert.equal(api.records.length,30);
  const graphMalformed=replace('validate();',"validate();CONNECTIONS.causal[0][0]='missing';validate();");assert.throws(()=>evaluate(graphMalformed),error=>{assert.equal(error.name,'Error');assert.match(error.message,/Invalid Unit 8/);assert.match(error.message,/unresolved connection/);return true;});
  const malformed=replace('validate();',"STUDY_MANIFEST[0][0]=Symbol('bad');validate();validate();");assert.throws(()=>evaluate(malformed),error=>{assert.equal(error.name,'Error');assert.match(error.message,/Invalid Unit 8/);assert.match(error.message,/invalid stable ID/);return true;});
});

const localCausalPairs=[...expectedLocations.keys()].flatMap(location=>{
  const local=expectedManifest.filter(record=>record[1]===location).sort((a,b)=>a[2]-b[2]);
  return [[local[0][0],local[1][0]],[local[1][0],local[2][0]]];
});
const crossLocationCausalPairs=[
  ['apwh-u8-moscow-security-buffer-soviet-bloc','apwh-u8-berlin-occupation-ideological-division'],
  ['apwh-u8-beijing-civil-war-land-communist-victory','apwh-u8-saigon-partition-containment-escalation'],
  ['apwh-u8-moscow-gorbachev-reform-soviet-dissolution','apwh-u8-berlin-wall-nonintervention-reunification'],
  ['apwh-u8-accra-panafricanism-nonaligned-state-building','apwh-u8-johannesburg-pressure-negotiation-democratic-transition'],
];
const expectedRelatedPairs=[
  ['apwh-u8-berlin-blockade-airlift-two-germanies','apwh-u8-havana-missile-crisis-nuclear-limits','Compare escalation and restraint in Berlin and Cuba: both crises tested superpower resolve without direct war, but Berlin used an airlift against a blockade while Cuba used a quarantine and reciprocal nuclear bargaining.'],
  ['apwh-u8-beijing-civil-war-land-communist-victory','apwh-u8-havana-batista-inequality-revolution','Compare land, nationalism, political coalitions, and relations with the United States: China emerged from a long civil war with early Soviet ties, while Cuba began as a broader anti-Batista coalition and aligned with the Soviet Union after revolutionary conflict with the United States.'],
  ['apwh-u8-delhi-independence-partition-displacement','apwh-u8-accra-negotiated-independence','Compare mass nationalism, negotiated imperial withdrawal, inherited institutions, and early state building in India and Ghana; both later pursued active nonalignment, which was not neutrality, while India also experienced Partition and vast displacement.'],
  ['apwh-u8-accra-negotiated-independence','apwh-u8-algiers-fln-war-counterinsurgency','Compare negotiated and armed paths to sovereignty: mass politics and elections gave Ghanaian leaders leverage for phased British withdrawal, while settler colonial resistance to reform pushed the FLN and France into a destructive independence war.'],
  ['apwh-u8-algiers-settler-colonialism-blocked-reform','apwh-u8-johannesburg-apartheid-legal-order','Compare minority rule, land and citizenship restrictions, resistance, and international pressure while distinguishing Algeria’s war to leave French colonial rule from South Africa’s negotiated transition within an existing state.'],
];

test('publishes the exact Unit 8 directed causal graph and reciprocal comparison graph',()=>{
  const api=evaluate(),byId=new Map(api.records.map(record=>[record.id,record]));
  const actualCausal=api.records.flatMap(record=>record.effectStudyPointIds.map(target=>[record.id,target]));
  const expectedCausal=[...localCausalPairs,...crossLocationCausalPairs];
  assert.deepEqual(clone(actualCausal.map(pair=>pair.join('|')).sort()),expectedCausal.map(pair=>pair.join('|')).sort());
  assert.equal(actualCausal.length,24);assert.equal(new Set(actualCausal.map(pair=>pair.join('|'))).size,24);
  for(const [sourceId,targetId] of actualCausal){const sourceRecord=byId.get(sourceId),targetRecord=byId.get(targetId);assert.ok(targetRecord);assert.ok(targetRecord.causeStudyPointIds.includes(sourceId));assert.equal(typeof sourceRecord.connectionNotes[targetId],'string');assert.ok(sourceRecord.connectionNotes[targetId].length>40);assert.equal(targetRecord.connectionNotes[sourceId],sourceRecord.connectionNotes[targetId]);assert.doesNotMatch(sourceRecord.connectionNotes[targetId],/^This happened before/i);}
  for(const [left,right,note] of expectedRelatedPairs){const leftRecord=byId.get(left),rightRecord=byId.get(right);assert.ok(leftRecord.relatedStudyPointIds.includes(right));assert.ok(rightRecord.relatedStudyPointIds.includes(left));assert.equal(leftRecord.connectionNotes[right],note);assert.equal(rightRecord.connectionNotes[left],note);}
  assert.equal(api.records.reduce((sum,record)=>sum+record.relatedStudyPointIds.length,0),10);
});

const expectedUnitCards={
  context:{id:'apwh-u8-context-allied-victory-bipolar-decolonizing-world',kind:'context',role:'Unit 8 Context Card',title:'From Allied Victory to a Bipolar and Decolonizing World',examSkills:['Contextualization','Causation'],summary:'World War II weakened European imperial capacity, elevated the United States and Soviet Union, left armies occupying strategic regions, strengthened anticolonial demands, and created the United Nations alongside a Security Council whose veto structure could freeze conflicts important to either superpower.',prompt:'How did the outcomes of World War II create both superpower rivalry and new opportunities for decolonization?',takeaways:['The United States and Soviet Union emerged with unmatched military and political influence.','European empires survived the war with reduced resources and legitimacy.','Nuclear weapons and the United Nations changed how states pursued conflict and sovereignty.']},
  synthesis:{id:'apwh-u8-synthesis-bipolar-competition-globalized-order',kind:'synthesis',role:'Unit 8 Synthesis Card',title:'From Bipolar Competition to a Globalized Order',examSkills:['Causation','CCOT'],summary:'Soviet collapse ended the second superpower system without ending proxy-war legacies, contested borders, uneven development, or demands for political autonomy. Former socialist states, newly independent states, and market-reforming communist governments entered a more integrated system of trade, finance, production, communication, and migration under unequal conditions.',prompt:'Which Cold War and decolonization outcomes shaped who benefited from globalization after 1991?',takeaways:['The Soviet bloc ended, but borders, alliances, military institutions, and conflict legacies persisted.','New states entered global markets with unequal infrastructure, debt, and commodity dependence.','Market reform changed socialist economies without producing identical political systems.']},
};

test('publishes the exact immutable Unit 8 context and synthesis cards',()=>{
  const api=evaluate();assert.deepEqual(clone(api.unitCards),expectedUnitCards);assert.equal(Object.isFrozen(api.unitCards),true);
  for(const [kind,card] of Object.entries(expectedUnitCards)){assert.equal(api.getUnitCard(kind),api.unitCards[kind]);assert.equal(api.getUnitCard(card.id),api.unitCards[kind]);assert.equal(Object.isFrozen(api.unitCards[kind]),true);assert.equal(Object.isFrozen(api.unitCards[kind].examSkills),true);assert.equal(Object.isFrozen(api.unitCards[kind].takeaways),true);assert.equal(Object.hasOwn(api.unitCards[kind],'skills'),false);}
});

test('rejects graph or card drift before publication',()=>{
  assertInvalid(replace("Occupation policies and Western currency reform triggered the Soviet blockade; the Allied airlift sustained West Berlin and hardened Germany’s political division.","This happened before the next event and shaped its chronology."),/causal connection does not match|causal mechanism/);
  assertInvalid(replace("related:[","related:[[\'apwh-u8-berlin-occupation-ideological-division\',\'apwh-u8-berlin-blockade-airlift-two-germanies\',\'Cross category.\'],"),/cross-category connection/);
  assertInvalid(replace("kind:'context'","kind:'synthesis'"),/card kind/);
  assertInvalid(replace("role:'Unit 8 Context Card'","role:''"),/card role|malformed card/);
  assertInvalid(replace("examSkills:['Contextualization','Causation']","examSkills:['Causation','Causation']"),/card skills/);
  assertInvalid(replace("synthesis:{id:'apwh-u8-synthesis-bipolar-competition-globalized-order'","synthesis:{id:'apwh-u8-context-allied-victory-bipolar-decolonizing-world'"),/duplicate card ID/);
  assertInvalid(replace("title:'From Allied Victory to a Bipolar and Decolonizing World'","title:'Arbitrary English Title'"),/card contract/);
  assertInvalid(replace('validate();',"Object.defineProperty(UNIT_CARD_MANIFEST.context.takeaways,'0',{enumerable:false});validate();"),/card takeaways/);
});

test('keeps the ordered Unit 8 source ledger exact and locator-specific',()=>{
  const intro='# APWH Unit 8 Location Study Source Ledger\n\nThe learner records use edition-neutral locators in AMSCO AP World History Unit 8 and the College Board framework effective Fall 2026. Map pins are representative anchors; a named city does not imply that every national or regional process occurred only there. Causal and comparison notes distinguish mechanisms from chronology and preserve the agency and differences of each case.\n\n';
  assert.ok(ledger.startsWith(intro));const lines=ledger.trimEnd().split('\n');assert.equal(lines.length,36);assert.equal(lines[4],'| Stable ID | AP topic assignment | Main event | Source locator | Claims covered |');assert.equal(lines[5],'| --- | --- | --- | --- | --- |');
  const rows=lines.slice(6).map(row=>row.split('|').slice(1,-1).map(cell=>cell.trim()));assert.equal(rows.length,30);assert.deepEqual(rows.map(row=>row[0]),expectedManifest.map(record=>record[0]));assert.deepEqual(rows.map(row=>row[1]),expectedManifest.map(record=>record[8].join(', ')));assert.deepEqual(rows.map(row=>row[2]),expectedManifest.map(record=>record[7]));assert.deepEqual(rows.map(row=>row[3]),expectedManifest.map(record=>L(record[8])));
  for(const cells of rows){assert.equal(cells.length,5);assert.match(cells[1],/^8\.[1-9](, 8\.[1-9])*$/);assert.match(cells[3],/^AMSCO AP World History, Unit 8, Topics? 8\.[1-9]/);assert.doesNotMatch(cells[3],/(page|p\.\s*\d|whole book|chapter)/i);assert.ok(cells[4].length>=60);}
});

test('keeps representative-anchor and cross-case caveats in the Unit 8 ledger',()=>{
  const claimsById=new Map(ledger.trimEnd().split('\n').slice(6).map(row=>{const cells=row.split('|').slice(1,-1).map(cell=>cell.trim());return [cells[0],cells[4]];}));
  assert.match(claimsById.get('apwh-u8-delhi-independence-partition-displacement'),/Punjab and Bengal/);assert.match(claimsById.get('apwh-u8-delhi-independence-partition-displacement'),/Delhi is a representative national anchor/);
  assert.match(claimsById.get('apwh-u8-saigon-withdrawal-reunification-war-costs'),/Saigon was renamed Ho Chi Minh City/);
  assert.match(claimsById.get('apwh-u8-algiers-settler-colonialism-blocked-reform'),/Algiers is a representative anchor/);
  assert.match(claimsById.get('apwh-u8-johannesburg-apartheid-legal-order'),/Johannesburg is a representative national anchor/);
  assert.match(claimsById.get('apwh-u8-accra-negotiated-independence'),/negotiated and armed paths/);assert.match(claimsById.get('apwh-u8-accra-negotiated-independence'),/project-authored comparison/);
  assert.match(claimsById.get('apwh-u8-berlin-blockade-airlift-two-germanies'),/comparison with Cuba is project-authored analysis/);assert.match(claimsById.get('apwh-u8-beijing-civil-war-land-communist-victory'),/China-Cuba comparison is project-authored analysis/);assert.match(claimsById.get('apwh-u8-delhi-independence-partition-displacement'),/India-Ghana comparison is project-authored analysis/);assert.match(claimsById.get('apwh-u8-johannesburg-pressure-negotiation-democratic-transition'),/Algeria-South Africa comparison is project-authored analysis/);
});

test('rejects source-ledger structural, vague-locator, page-number, and trailing-content regressions',()=>{
  const valid=ledger.trimEnd(),requiredCaveats=['Punjab and Bengal','Delhi is a representative national anchor','Saigon was renamed Ho Chi Minh City','Algiers is a representative anchor','Johannesburg is a representative national anchor','comparison with Cuba is project-authored analysis','China-Cuba comparison is project-authored analysis','India-Ghana comparison is project-authored analysis','project-authored comparison distinguishes negotiated and armed paths','Algeria-South Africa comparison is project-authored analysis'],isValid=candidate=>{const lines=candidate.split('\n'),rows=lines.slice(6);return lines.length===36&&lines[4]==='| Stable ID | AP topic assignment | Main event | Source locator | Claims covered |'&&lines[5]==='| --- | --- | --- | --- | --- |'&&rows.length===30&&requiredCaveats.every(caveat=>candidate.includes(caveat))&&rows.every((row,index)=>{if(!row.endsWith('|'))return false;const cells=row.split('|').slice(1,-1).map(cell=>cell.trim());return cells.length===5&&cells[0]===expectedManifest[index][0]&&cells[1]===expectedManifest[index][8].join(', ')&&cells[2]===expectedManifest[index][7]&&cells[3]===L(expectedManifest[index][8])&&cells[4].length>=60;});};
  const firstRow=valid.split('\n')[6],secondId=expectedManifest[1][0];assert.equal(isValid(valid),true);for(const candidate of [valid.replace('| Main event |','| Event |'),valid.replace('AMSCO AP World History, Unit 8, Topics','AMSCO'),valid.replace('AMSCO AP World History, Unit 8, Topics','AMSCO AP World History, Unit 8, Topics p. 12'),valid.replace(`${firstRow}\n`,''),valid.replace(secondId,expectedManifest[0][0]),valid.replace('world-event-29-8','world-event-29-9'),valid.replace('| Claims covered |','| Extra | Claims covered |'),valid.replace('Punjab and Bengal','Punjab plus Bengal'),`${valid}\ntrailing garbage`,valid.replace(/\|$/,'|junk')]){assert.notEqual(candidate,valid);assert.equal(isValid(candidate),false);}
});
